"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
const cloudDataRuntime = fs.readFileSync(path.join(root, "cloud-data-runtime.js"), "utf8");
const dataStore = fs.readFileSync(path.join(root, "data-store.js"), "utf8");
const drive = fs.readFileSync(path.join(root, "drive-sync.js"), "utf8");
const tasks = fs.readFileSync(path.join(root, "tasks-store.js"), "utf8");
const peopleStore = fs.readFileSync(path.join(root, "people-store.js"), "utf8");
const jira = fs.readFileSync(path.join(root, "jira-store.js"), "utf8");
const reminders = fs.readFileSync(path.join(root, "reminders-store.js"), "utf8");
const aiClient = fs.readFileSync(path.join(root, "ai-assistant.js"), "utf8");
const jiraCloudClient = fs.readFileSync(path.join(root, "jira-cloud.js"), "utf8");
const outlookCalendarClient = fs.readFileSync(path.join(root, "outlook-calendar.js"), "utf8");
const googleCalendarClient = fs.readFileSync(path.join(root, "google-calendar.js"), "utf8");
const weatherClient = fs.readFileSync(path.join(root, "weather-client.js"), "utf8");
const authValidation = fs.readFileSync(path.join(root, "auth-validation.js"), "utf8");
const supabaseCloudClient = fs.readFileSync(path.join(root, "supabase-cloud.js"), "utf8");
const jiraEdgeFunction = fs.readFileSync(path.join(root, "supabase", "functions", "jira-proxy", "index.ts"), "utf8");
const jiraVaultMigration = fs.readFileSync(path.join(root, "supabase", "migrations", "20260810190000_jira_credentials_vault.sql"), "utf8");
const accessLogEdgeFunction = fs.readFileSync(path.join(root, "supabase", "functions", "access-log", "index.ts"), "utf8");
const accessLogMigration = fs.readFileSync(path.join(root, "supabase", "migrations", "20260813090000_user_access_logs.sql"), "utf8");
const deferredWorkspaceMigration = fs.readFileSync(path.join(root, "supabase", "migrations", "20260814100000_defer_workspace_until_email_confirmation.sql"), "utf8");
const aiServer = fs.readFileSync(path.join(root, "server.js"), "utf8");
const css = fs.readFileSync(path.join(root, "styles.css"), "utf8");
const taskDetailHtml = fs.readFileSync(path.join(root, "task-detail.html"), "utf8");
const taskDetailApp = fs.readFileSync(path.join(root, "task-detail.js"), "utf8");
const taskTypeReportHtml = fs.readFileSync(path.join(root, "task-type-report.html"), "utf8");
const taskTypeReportApp = fs.readFileSync(path.join(root, "task-type-report.js"), "utf8");
const deleteEffortBlock = app.slice(app.indexOf("async function deleteEffortEntry"), app.indexOf("\n  function render()", app.indexOf("async function deleteEffortEntry")));
const effortModalSubmitBlock = app.slice(app.indexOf('effortEditModalForm.addEventListener("submit"'), app.indexOf("\n  function updateTimesheetControls", app.indexOf('effortEditModalForm.addEventListener("submit"')));

assert.doesNotMatch([app, dataStore, tasks, peopleStore, jira, reminders, drive, aiClient, jiraCloudClient, outlookCalendarClient, weatherClient].join("\n"), /localStorage\.(?:getItem|setItem|removeItem)/, "App data and user preferences must not persist in localStorage");
assert.match(supabaseCloudClient, /async function getUserSettings[\s\S]*async function updateUserSettings[\s\S]*from\("user_settings"\)/, "User preferences must be read from and written to Supabase user_settings");
assert.match(app, /function queueCloudUserSettings[\s\S]*SupabaseCloud\.updateUserSettings[\s\S]*applyCloudUserSettings\(bundle\.settings/, "Cloud preferences must load automatically and save to Supabase");
assert.ok(["themeHeaderMenu", "violet", "ocean", "forest", "sunset", "midnight", "graphite"].every((token) => html.includes(token)), "Header theme menu must expose all supported palettes");
assert.ok(["APP_THEMES", "async function applyTheme", "document.documentElement.dataset.theme", "queueCloudUserSettings({ theme })"].every((token) => app.includes(token)), "Theme selection must update the document and persist to Supabase settings");
assert.ok(app.includes('applyTheme(cloudUserSettings.theme || "violet")'), "Saved theme must load with cloud user settings");
assert.ok(taskDetailApp.includes('bundle.settings?.theme') && taskTypeReportApp.includes('bundle.settings?.theme'), "Task detail and type report pages must inherit the saved Supabase theme");
assert.ok([':root[data-theme="ocean"]', ':root[data-theme="forest"]', ':root[data-theme="sunset"]'].every((token) => css.includes(token)), "All application themes must define shared design tokens");
assert.ok([':root[data-theme="midnight"]', ':root[data-theme="graphite"]', 'color-scheme: dark'].every((token) => css.includes(token)), "Dark themes must define accessible dark color tokens");
assert.ok(app.includes('meta.dark ? "dark" : "light"'), "Theme selection must update the browser color scheme for dark palettes");
assert.ok(["var(--header-start)", ".home-kpi-primary", "var(--brand-accent)"].every((token) => css.includes(token)), "Core application surfaces must consume the shared theme tokens");

const requiredIds = [
  "todayLabel", "weatherIcon", "weatherLocationMenu", "weatherLocationLabel", "weatherLocationForm", "weatherLocationInput", "weatherUseDeviceLocation", "weatherLocationStatus", "weatherLocationResults", "weatherTemperature", "weatherCondition", "weatherMeta", "refreshWeather",
  "homeView", "homeWeekLabel", "homeWeeklyHours", "homeWeeklyGoal", "homeWeeklyEntryCount",
  "homePlannedTasks", "homeInProgressTasks", "weeklyEffortChart", "taskStatusChart",
  "jiraEffortChart", "homeOpenTaskCount", "homePendingTaskList", "homeJiraStatusTitle", "homeJiraStatusChart", "homeAssignedJiraTitle", "homeJiraStatusFilter",
  "homeJiraIssueCount", "refreshHomeJiraIssues", "homeJiraIssueStatus", "homeJiraIssueList", "homeJiraIssueEmpty",
  "reminderPanelTitle", "reminderOpenCount", "openReminderModal", "reminderTickerWindow", "reminderModal", "reminderModalTitle", "closeReminderModal", "reminderForm", "reminderId", "reminderTextInput",
  "reminderDateInput", "reminderImportanceInput", "reminderOptions", "reminderSubmitLabel", "cancelReminderEdit", "reminderFormMessage", "reminderEmptyState", "reminderList",
  "outlookCalendarTitle", "showGoogleCalendar", "showOutlookCalendar", "outlookCalendarConnection", "connectOutlookCalendar", "refreshOutlookCalendar", "disconnectOutlookCalendar", "calendarPreviousMonth", "calendarToday", "calendarNextMonth", "outlookCalendarPeriod", "outlookCalendarSettings", "outlookClientId", "outlookTenantId", "saveOutlookSettings", "outlookRedirectUri", "googleCalendarSettings", "googleCalendarClientState", "outlookCalendarStatus", "outlookCalendarEmpty", "outlookCalendarList",
  "openAiAssistant", "aiAssistantPanel", "aiAssistantTitle", "aiAssistantStatus", "closeAiAssistant",
  "aiAssistantMessages", "aiAssistantForm", "aiAssistantInput", "aiAssistantInputCount", "sendAiAssistantMessage",
  "aiAssistantEndpoint", "saveAiAssistantEndpoint",
  "effortForm", "entryId", "dateInput", "hoursInput",
  "descriptionInput", "filterDateInput", "entryList", "entryTemplate",
  "dailyTotal", "dailyDays", "effortWeekHours", "effortWeekDays", "effortMonthHours", "effortMonthDays", "grandTotal", "effortTotalDays", "entryCount", "formMessage", "lastBackupTime",
  "themeHeaderMenu", "headerThemeMenuLabel", "themePanelTitle", "themeSelectionBadge", "themeOptionList", "themeStatus",
  "driveHeaderMenu", "headerDriveMenuLabel", "headerDriveMenuBadge", "driveCompactPanel", "driveCompactTitle", "driveConnectionBadge", "driveSettingsSummary", "driveClientIdPreview", "editDriveSettings", "driveSettingsEditor", "cancelDriveSettings", "skipInitialRestore",
  "loginScreen", "loginScreenTitle", "loginScreenDescription", "loginScreenStatus", "loginScreenForm", "loginScreenEmail", "loginScreenPassword", "loginScreenConfirmPasswordField", "loginScreenConfirmPassword", "loginScreenPasswordRules", "loginScreenSignInMode", "loginScreenSignIn", "loginScreenSignUp", "loginScreenForgotPassword", "loginVerificationPanel", "loginVerificationEmail", "loginResendVerification", "loginVerificationBack",
  "supabaseHeaderMenu", "headerSupabaseMenuLabel", "headerSupabaseMenuBadge", "supabaseConnectionBadge", "supabaseStatus", "supabaseAuthForm", "supabaseEmail", "supabasePassword", "supabaseConfirmPasswordField", "supabaseConfirmPassword", "supabasePasswordRules", "supabaseSignInMode", "supabaseSignIn", "supabaseSignUp", "supabaseForgotPassword", "supabaseVerificationPanel", "supabaseVerificationEmail", "supabaseResendVerification", "supabaseVerificationBack", "supabaseRecoveryForm", "supabaseNewPassword", "supabaseSignedInPanel", "supabaseUserEmail", "supabaseOrganizationName", "supabaseLastSync", "supabasePull", "supabaseSignOut", "cloudDataGate", "cloudDataGateTitle", "cloudDataGateMessage", "openSupabaseFromGate",
  "tasksView", "taskForm", "taskTitleInput", "taskDueDateInput", "taskStatusInput", "taskDescriptionInput", "taskDocumentsInput", "taskDocumentSelectionSummary", "taskDocumentList",
  "taskParentTaskInput", "taskAssigneePicker", "taskAssigneePickerButton", "taskAssigneePickerValue", "taskAssigneePickerDropdown", "taskAssigneeSearchInput", "taskAssigneeSearchStatus", "taskAssigneeOptionList", "taskAssigneeInput", "taskTypeInput", "taskPriorityInput", "taskYearInput", "taskQuarterInput", "taskPlanImport",
  "openTaskPlanPaste", "taskPlanImportModal", "taskPlanPasteForm", "taskPlanTextInput", "taskPlanPasteMessage",
  "taskList", "taskTemplate", "taskTypeGroupTemplate", "taskCreateView", "taskReportView", "taskDetailView", "taskDetailTitle",
  "taskDetailDescription", "taskDetailParentItem", "taskDetailAssignee", "taskDetailType", "taskDetailPriority", "taskDetailPlan", "taskDetailSubtaskList", "taskDetailSubtaskCount", "addSubtaskButton", "taskTypeFilter", "taskStatusFilter", "taskFilterEmpty", "reviseTaskButton", "backToTaskReport", "taskReportCount", "taskReportTableWrap",
  "timesheetView", "timesheetPeriod", "timesheetReferenceDate", "timesheetStartDate",
  "timesheetEndDate", "includeWeekends", "addTimesheetEffort", "syncJiraWorklogs", "timesheetJiraSyncStatus", "timesheetTable", "timesheetTotalHours",
  "timesheetGrouping",
  "jiraItemPicker", "jiraItemPickerButton", "jiraItemPickerValue", "jiraItemPickerDropdown", "jiraItemSearchInput", "jiraItemSearchCount", "jiraItemOptionList", "jiraItemInput", "jiraView", "jiraForm", "jiraNameInput", "jiraSubmitButton", "jiraSubmitLabel",
  "jiraList", "jiraTemplate", "jiraHtmlImport",
  "jiraHeaderMenu", "headerJiraMenuLabel", "headerJiraMenuBadge", "jiraCloudTitle", "jiraOAuthBadge", "connectJiraOAuth", "disconnectJiraOAuth", "jiraCredentialTitle", "jiraCredentialBadge", "jiraCredentialStatus", "jiraCredentialBaseUrl", "jiraCredentialEmail", "jiraCredentialToken", "getJiraApiToken", "saveJiraCredentials", "removeJiraCredentials", "jiraSyncJql", "testJiraConnection", "syncJiraIssues", "jiraAutoWorklog", "jiraCloudStatus",
  "jiraSearchInput", "refreshJiraNavigator", "selectAllJiraItems", "clearJiraItemSelection", "deleteSelectedJiraItems", "jiraSelectionCount", "jiraNavigatorSyncStatus", "jiraColumnManager", "jiraColumnOptions", "autoFitJiraColumns", "resetJiraColumns", "jiraColumnStatus", "jiraIssueTable", "jiraTableHeaderRow", "jiraTableBody", "jiraItemsView", "jiraRequestsView", "jiraItemsSubtabCount", "jiraRequestsSubtabCount", "jiraAssigneeFilterPicker", "jiraAssigneeFilterButton", "jiraAssigneeFilterValue", "jiraAssigneeFilterDropdown", "jiraAssigneeFilterSearch", "jiraAssigneeFilterSearchStatus", "jiraAssigneeFilterOptions", "jiraAssigneeFilterStatus", "clearJiraAssigneeFilter", "jiraRequestsAssigneeFilterPicker", "jiraRequestsAssigneeFilterButton", "jiraRequestsAssigneeFilterValue", "jiraRequestsAssigneeFilterDropdown", "jiraRequestsAssigneeFilterSearch", "jiraRequestsAssigneeFilterSearchStatus", "jiraRequestsAssigneeFilterOptions", "jiraRequestsAssigneeFilterStatus", "clearJiraRequestsAssigneeFilter", "jiraRequestsTitle", "jiraRequestsSearch", "jiraRequestTotal", "jiraRequestStatusFilters", "selectAllJiraRequestStatuses", "clearJiraRequestStatuses", "jiraRequestBoardStatus", "jiraRequestsEmpty", "jiraRequestBoard", "effortEditModal", "effortEditModalForm", "modalEntrySelect",
  "modalJiraPicker", "modalJiraPickerButton", "modalJiraPickerValue", "modalJiraPickerDropdown", "modalJiraSearchInput", "modalJiraSearchCount", "modalJiraOptionList", "modalJiraInput", "modalDateInput", "modalHoursInput", "modalDescriptionInput", "effortEditModalSubmitLabel", "deleteEffortModal",
  "modalRepeatEntryToggleField", "modalRepeatEntryToggle",
  "teamView", "peopleView", "peopleTabCount", "syncJiraUsers", "jiraPeopleSyncTitle", "jiraPeopleSyncStatus", "jiraPeopleCount", "manualPeopleCount", "personForm", "personId", "personJiraIdentity", "personJiraIdentityAvatar", "personJiraIdentityName", "personJiraIdentityAccount", "personFullNameInput", "personEmailInput", "personTitleInput", "personRoleInput", "personManagerInput", "personFormMessage", "personFormTitle", "personSubmitLabel", "cancelPersonEdit", "peopleListTitle", "peopleCount", "peopleSearchInput", "peopleSourceFilter", "peopleEmptyState", "peopleFilterEmpty", "peopleList",
  "organizationView", "organizationLeaderFilter", "organizationWorkloadTitle", "organizationTaskStats", "organizationTaskEmpty", "organizationTaskTableWrap", "organizationTaskList",
  "accessLogTab", "accessLogView", "accessLogTitle", "accessLogTotal", "accessLogUserCount", "accessLogActiveCount", "accessLogAverageDuration", "refreshAccessLogs", "accessLogFrom", "accessLogTo", "accessLogSearch", "accessLogStatusFilter", "accessLogStatus", "accessLogEmpty", "accessLogTableWrap", "accessLogTableBody", "adminUserTitle", "refreshAdminUsers", "adminUserSearch", "adminUserCount", "adminUserStatus", "adminUserEmpty", "adminUserTableWrap", "adminUserTableBody",
];

for (const id of requiredIds) {
  assert.match(html, new RegExp(`id=["']${id}["']`), `Eksik DOM sözleşmesi: #${id}`);
}

for (const id of ["taskDetailPageContent", "taskDetailPageErrorTitle", "taskDetailPageErrorMessage", "detailPageTitle", "detailPageTaskType", "detailPagePriority", "detailPageStatus", "detailPageCompleted", "detailPageOverviewTask", "detailPageParent", "detailPageAssignee", "detailPagePriorityValue", "detailPagePlan", "detailPageDueDate", "detailPageStatusValue", "detailPageDescription", "detailPageDocumentCount", "detailPageDocumentList", "detailPageSubtaskList", "detailPageRevise"]) {
  assert.match(taskDetailHtml, new RegExp(`id=["']${id}["']`), `Eksik görev detay sayfası sözleşmesi: #${id}`);
}

for (const id of ["taskTypeReportTitle", "taskTypeReportBackLink", "taskTypeReportErrorTitle", "taskTypeReportErrorMessage", "taskTypeReportContent", "taskTypeReportTotal", "taskTypeReportOpen", "taskTypeReportInProgress", "taskTypeReportCompleted", "taskTypeReportColumnManager", "taskTypeReportColumnOptions", "resetTaskTypeReportColumns", "taskTypeReportFitToggle", "taskTypeReportColumnStatus", "taskTypeReportScroll", "taskTypeReportTable", "taskTypeReportHeaderRow", "taskTypeReportBody"]) {
  assert.match(taskTypeReportHtml, new RegExp(`id=["']${id}["']`), `Eksik görev tipi raporu sözleşmesi: #${id}`);
}

assert.ok(html.indexOf('src="cloud-data-runtime.js') < html.indexOf('src="data-store.js') && html.indexOf('src="data-store.js') < html.indexOf('src="app.js'), "Bellek tabanlı bulut çalışma katmanı veri mağazalarından önce yüklenmeli");
assert.ok(html.indexOf('src="vendor/msal-browser.min.js') < html.indexOf('src="outlook-calendar.js') && html.indexOf('src="outlook-calendar.js') < html.indexOf('src="app.js'), "MSAL ve Outlook Takvim istemcileri uygulamadan önce yüklenmeli");
assert.ok(html.indexOf('src="drive-sync.js') < html.indexOf('src="google-calendar.js') && html.indexOf('src="google-calendar.js') < html.indexOf('src="app.js'), "Drive ayarları ve Google Takvim istemcisi uygulamadan önce yüklenmeli");
assert.ok(html.indexOf('src="weather-client.js') < html.indexOf('src="app.js'), "Hava durumu istemcisi uygulamadan önce yüklenmeli");
assert.match(weatherClient, /geocoding-api\.open-meteo\.com\/v1\/search[\s\S]*api\.open-meteo\.com\/v1\/forecast/, "Hava durumu istemcisi resmi Open-Meteo konum ve tahmin uçlarını kullanmalı");
assert.match(weatherClient, /current:[\s\S]*temperature_2m[\s\S]*apparent_temperature[\s\S]*relative_humidity_2m[\s\S]*weather_code[\s\S]*wind_speed_10m[\s\S]*daily:[\s\S]*temperature_2m_max[\s\S]*temperature_2m_min/, "Hava durumu istemcisi kompakt kart için güncel ve günlük değerleri istemeli");
assert.doesNotMatch(weatherClient, /api[_-]?key|Authorization/i, "Anahtarsız hava durumu entegrasyonu tarayıcıda gizli bilgi taşımamalı");
assert.match(app, /function useDeviceWeatherLocation[\s\S]*getCurrentPosition[\s\S]*weatherUseDeviceLocation"\)\.addEventListener\("click"/, "Cihaz konumu yalnızca kullanıcı düğmeye bastığında istenmeli");
assert.match(app, /queueCloudUserSettings\(\{ weatherLocation \}\)/, "Seçilen hava durumu konumu Supabase kullanıcı ayarına kaydedilmeli");
assert.match(app, /applyWeatherLocationSetting\(cloudUserSettings\.weatherLocation/, "Kayıtlı hava durumu konumu Supabase kullanıcı ayarından yüklenmeli");
assert.match(css, /header-weather-card[^{]*\{[^}]*grid-template-columns[\s\S]*weather-location-popover[^{]*\{[^}]*position:\s*absolute[\s\S]*@media\s*\(max-width:\s*600px\)[\s\S]*header-weather-card/, "Tarih ve hava durumu kartı masaüstü ve mobilde duyarlı olmalı");
assert.ok(html.indexOf('src="vendor/supabase.js') < html.indexOf('src="supabase-cloud.js') && html.indexOf('src="supabase-cloud.js') < html.indexOf('src="app.js'), "Sabitlenmiş Supabase SDK ve bulut istemcisi uygulamadan önce yüklenmeli");
assert.ok(html.indexOf('src="auth-validation.js') < html.indexOf('src="app.js'), "Saf hesap doğrulama katmanı uygulamadan önce yüklenmeli");
assert.match(supabaseCloudClient, /sb_publishable_[A-Za-z0-9_-]+/, "Tarayıcı Supabase bağlantısı modern publishable key kullanmalı");
assert.doesNotMatch(supabaseCloudClient, /service_role|sb_secret_|SUPABASE_SERVICE_ROLE/, "Supabase secret veya service-role anahtarı tarayıcı koduna yazılmamalı");
assert.match(supabaseCloudClient, /signUp[\s\S]*emailRedirectTo[\s\S]*signInWithPassword[\s\S]*resetPasswordForEmail[\s\S]*updateUser/, "Supabase e-posta kayıt, giriş, doğrulama ve şifre yenileme akışları bulunmalı");
assert.match(html, /id="loginScreenSignInMode"[\s\S]*id="loginScreenSignUp"[\s\S]*id="loginScreenConfirmPassword"[\s\S]*id="loginScreenSignIn"[^>]*type="submit"/, "Giriş ve hesap oluşturma modları ayrılmalı; seçilen işlem form submit ile çalışmalı");
assert.match(app, /function setSupabaseAuthMode[\s\S]*supabaseAuthMode === "signup"[\s\S]*autocomplete = signingUp \? "new-password" : "current-password"[\s\S]*function validateAuthForm/, "Kayıt modu alanları ve autocomplete değerleri merkezi olarak yönetilmeli");
assert.match(authValidation, /MIN_PASSWORD_LENGTH = 8[\s\S]*rawPassword\.length < MIN_PASSWORD_LENGTH[\s\S]*rawPassword !== rawPassword\.trim\(\)[\s\S]*rawPassword !== rawConfirmation/, "Sekiz karakter, dış boşluk ve şifre tekrarı saf doğrulama katmanında denetlenmeli");
assert.match(app, /function validateAuthForm[\s\S]*AuthValidation\.validate[\s\S]*if \(validation\.valid[\s\S]*function submitSupabaseCredentials/, "Doğrulama başarılı olmadan kayıt veya giriş isteği gönderilmemeli");
assert.match(app, /loginScreenForm"\)\.addEventListener\("submit"[\s\S]*submitSupabaseCredentials\("login"\)[\s\S]*supabaseAuthForm"\)\.addEventListener\("submit"[\s\S]*submitSupabaseCredentials\("header"\)/, "Enter tuşu aktif giriş veya kayıt modunu tek submit akışından çalıştırmalı");
assert.match(app, /function showVerificationPending[\s\S]*loginVerificationPanel[\s\S]*supabaseVerificationPanel[\s\S]*function resendVerificationEmail[\s\S]*resendSignUpConfirmation/, "Oturumsuz kayıt sonrası ayrı doğrulama ekranı ve yeniden gönderim akışı bulunmalı");
assert.match(supabaseCloudClient, /async function signUp[\s\S]*normalizedPassword\.length < 8[\s\S]*normalizedPassword !== normalizedPassword\.trim\(\)[\s\S]*async function resendSignUpConfirmation[\s\S]*auth\.resend/, "Supabase istemci katmanı da zayıf kayıt şifresini engelleyip doğrulama e-postasını yeniden gönderebilmeli");
assert.match(deferredWorkspaceMigration, /private\.provision_user_workspace[\s\S]*if exists \(select 1 from public\.user_settings[\s\S]*new\.email_confirmed_at is not null[\s\S]*after update of email_confirmed_at on auth\.users/, "Kişisel çalışma alanı yalnızca doğrulanmış kullanıcı için ve tek sefer oluşturulmalı");
assert.match(supabaseCloudClient, /organization_members[\s\S]*pullBundle[\s\S]*onConflict:\s*"organization_id,id"[\s\S]*pushBundle/, "Supabase senkronizasyonu organizasyon kapsamında güvenli upsert kullanmalı");
assert.match(html, /id="accessLogTab"\s+class="tab-button hidden"[\s\S]*id="accessLogView"\s+class="tab-view hidden"/, "Sistem logu sekmesi varsayılan olarak yalnızca yetkili kullanıcı için açılmak üzere gizli olmalı");
assert.match(app, /ACCESS_LOG_ADMIN_EMAIL\s*=\s*"selcuk\.dere@fit-global\.com"[\s\S]*function updateAccessLogVisibility[\s\S]*function loadAccessLogs/, "Log sekmesi yalnızca tanımlı yönetici hesabında görünmeli");
assert.match(app, /function startAccessTracking[\s\S]*trackAccess\("start"[\s\S]*setInterval\(sendAccessHeartbeat[\s\S]*function finishAccessTracking[\s\S]*trackAccess\("end"/, "Giriş, heartbeat ve çıkış hareketleri oturum süresini hesaplamak için kaydedilmeli");
assert.match(app, /pagehide[\s\S]*trackAccessOnUnload/, "Tarayıcı kapanışında çıkış kaydı keepalive isteğiyle denenmeli");
assert.match(supabaseCloudClient, /function invokeAccessLog[\s\S]*functions\.invoke\("access-log"[\s\S]*function listAccessLogs[\s\S]*function trackAccessOnUnload/, "Supabase istemcisi log yazma, listeleme ve kapanış akışlarını desteklemeli");
assert.match(html, /id="adminUserTitle"[\s\S]*id="refreshAdminUsers"[\s\S]*id="adminUserSearch"[\s\S]*id="adminUserTableBody"/, "Yönetici panelinde Supabase kullanıcı bakım tablosu bulunmalı");
assert.match(app, /function renderAdminUsers[\s\S]*function loadAdminUsers[\s\S]*SupabaseCloud\.listAdminUsers[\s\S]*function deleteAdminUser[\s\S]*SupabaseCloud\.deleteAdminUser/, "Yönetici kullanıcıları listelenip onaylı olarak silinebilmeli");
assert.match(app, /window\.prompt\([\s\S]*confirmation\.trim\(\)\.toLowerCase\(\)[\s\S]*expected\.toLowerCase\(\)/, "Kalıcı kullanıcı silme işleminde hedef e-posta veya kimlik yazılarak güçlü onay alınmalı");
assert.match(supabaseCloudClient, /function listAdminUsers\(\)[\s\S]*invokeAccessLog\("list-users"\)[\s\S]*function deleteAdminUser[\s\S]*invokeAccessLog\("delete-user"/, "Supabase istemcisi yönetici kullanıcı işlemlerini Edge Function üzerinden yapmalı");
assert.match(accessLogMigration, /create table public\.user_access_logs[\s\S]*ip_address inet[\s\S]*last_seen_at[\s\S]*enable row level security[\s\S]*selcuk\.dere@fit-global\.com/, "Erişim logu tablosu IP, heartbeat ve yöneticiye özel RLS politikası içermeli");
assert.match(accessLogMigration, /revoke all on table public\.user_access_logs from anon, authenticated[\s\S]*grant select on table public\.user_access_logs to authenticated/, "Standart kullanıcılar log tablosuna doğrudan yazamamalı");
assert.match(accessLogEdgeFunction, /admin\.auth\.getUser\(bearerToken\(req\)\)[\s\S]*email !== ADMIN_EMAIL[\s\S]*clientIp\(req\)[\s\S]*action === "heartbeat" \|\| action === "end"/, "Edge Function kullanıcı JWT'sini doğrulamalı, yönetici okumayı sınırlandırmalı ve IP'yi istek başlığından almalı");
assert.match(accessLogEdgeFunction, /action === "list-users" \|\| action === "delete-user"[\s\S]*admin\.auth\.admin\.listUsers[\s\S]*targetUserId === user\.id[\s\S]*admin\.auth\.admin\.deleteUser/, "Kullanıcı listeleme ve silme yalnızca sunucu tarafında yapılmalı; yönetici kendi hesabını silememeli");
assert.match(accessLogEdgeFunction, /organization_members[\s\S]*otherMemberCount[\s\S]*Önce sahipliği başka bir kullanıcıya aktarın[\s\S]*from\("organizations"\)[\s\S]*\.delete\(\)[\s\S]*deleteUser/, "Başka üyeleri olan çalışma alanları korunmalı ve kişisel alan kullanıcıdan önce güvenli biçimde temizlenmeli");
assert.doesNotMatch(accessLogEdgeFunction, /body\?\.(?:ip|ipAddress)|service_role\s*=|sb_secret_[A-Za-z0-9_-]+/, "IP istemci gövdesinden alınmamalı ve Edge Function içinde gerçek servis sırrı bulunmamalı");
assert.match(supabaseCloudClient, /async function applyChanges[\s\S]*TABLES\[collection\][\s\S]*\.upsert\(rows[\s\S]*removableIds[\s\S]*\.delete\(\)/, "Bellek değişiklikleri Supabase'e satır bazında eklenip silinebilmeli");
assert.match(html, /<meta\s+name="viewport"/i, "Mobil viewport tanımı eksik");
assert.match(css, /@media\s*\(max-width:\s*850px\)/, "Tablet kırılımı eksik");
assert.match(css, /@media\s*\(max-width:\s*600px\)/, "Mobil kırılımı eksik");
assert.match(html, /class="tab-button active"[^>]*data-tab="homeView"/, "Ana Sayfa varsayılan sekme olmalı");
assert.match(app, /function openTasksByStatus[\s\S]*taskStatusFilter[\s\S]*activateMainView\("tasksView"\)/, "Ana sayfa görev durumları ilgili durum filtresiyle görev raporunu açmalı");
assert.match(app, /task-chart-legend-item[\s\S]*openTasksByStatus\(status\)/, "Görev durumu açıklama satırları tıklanabilir olmalı");
assert.match(app, /selectedTaskStatus[\s\S]*task\.status === selectedTaskStatus[\s\S]*params\.set\("status", selectedTaskStatus\)/, "Görev raporu durum filtresini görev tipi detayına taşımalı");
assert.match(taskTypeReportApp, /selectedStatus[\s\S]*task\.status === selectedStatus/, "Görev tipi raporu seçili durum filtresini uygulamalı");
assert.match(taskTypeReportApp, /fromStatus[\s\S]*detailUrl\(task\.id, taskType, selectedStatus\)/, "Görev tipi raporu durum filtresini görev detayına taşımalı");
assert.match(html, /id="effortsView"\s+class="tab-view hidden"/, "Eforlar sekmesi ilk açılışta gizli olmalı");
assert.match(app, /function renderHomeDashboard/, "Ana Sayfa veri render fonksiyonu eksik");
assert.match(html, /id="homeAssignedJiraTitle"[\s\S]*id="homeJiraStatusFilter"[\s\S]*value="In Progress" selected[\s\S]*id="refreshHomeJiraIssues"[\s\S]*id="homeJiraIssueList"/, "Ana Sayfada varsayılan In Progress filtresiyle atanan JIRA paneli bulunmalı");
assert.match(app, /HOME_ASSIGNED_JIRA_JQL\s*=\s*"assignee = currentUser\(\) ORDER BY updated DESC"[\s\S]*function refreshHomeAssignedJiraIssues[\s\S]*JiraCloudClient\.syncIssues\(HOME_ASSIGNED_JIRA_JQL, 500\)/, "Ana Sayfa yalnızca oturum kullanıcısına atanan JIRA kayıtlarını canlı almalı");
assert.match(app, /function renderHomeAssignedJiraIssues[\s\S]*homeAssignedJiraStatus[\s\S]*home-jira-effort-button[\s\S]*openEffortCreateModal\(item\.id, isoToday\(\)\)/, "Ana Sayfa JIRA kayıtları statüye göre filtrelenmeli ve mevcut Timesheet popup'ıyla hızlı efor açmalı");
assert.match(app, /mainViewId === "homeView"[\s\S]*refreshHomeAssignedJiraIssues\(\)/, "Ana Sayfaya geçildiğinde atanan JIRA kayıtları yenilenmeli");
assert.match(html, /id="homeJiraStatusTitle"[\s\S]*id="homeJiraStatusChart"[\s\S]*id="homeAssignedJiraTitle"/, "JIRA durum grafiği atanan JIRA listesinin solunda bulunmalı");
assert.match(app, /function renderHomeJiraStatusChart[\s\S]*conic-gradient[\s\S]*task-chart-legend-item[\s\S]*homeAssignedJiraStatus = row\.status[\s\S]*renderHomeAssignedJiraIssues\(\)/, "JIRA durum grafiği dağılımı göstermeli ve statüye tıklanınca listeyi filtrelemeli");
assert.match(css, /home-jira-status-panel[^{]*\{[^}]*grid-column:\s*span\s*4[\s\S]*home-assigned-jira-panel[^{]*\{[^}]*grid-column:\s*span\s*8[\s\S]*home-jira-issue-row[^{]*\{[^}]*grid-template-columns/, "JIRA durum grafiği solda, atanan kayıtlar sağda duyarlı sütun düzeninde olmalı");
assert.match(app, /function buildAiAssistantContext[\s\S]*weeklyEfforts[\s\S]*tasks:[\s\S]*jiraItems:[\s\S]*reminders:/, "AI asistanı uygulama bağlamını güvenli ve sınırlı biçimde hazırlamalı");
assert.match(app, /AiAssistantClient\.ask[\s\S]*buildAiAssistantContext/, "AI sohbet formu güvenli istemciye bağlanmalı");
assert.match(aiClient, /fetch\(getEndpoint\(\)[\s\S]*message, context, history/, "AI istemcisi yalnızca backend endpoint'ine istek göndermeli");
assert.doesNotMatch(aiClient, /OPENAI_API_KEY|Authorization:\s*`Bearer/, "OpenAI API anahtarı tarayıcı kodunda bulunmamalı");
assert.match(aiServer, /process\.env\.OPENAI_API_KEY/, "AI backend anahtarı ortam değişkeninden okumalı");
assert.match(aiServer, /api\.openai\.com\/v1\/responses/, "AI backend Responses API'ye bağlanmalı");
assert.match(aiServer, /store:\s*false[\s\S]*reasoning:\s*\{\s*effort:\s*"low"/, "AI istekleri saklama kapalı ve düşük reasoning eforuyla gönderilmeli");
assert.match(app, /function renderReminders[\s\S]*ReminderStore\.list/, "Ana Sayfa hatırlatma listesi veri katmanına bağlanmalı");
assert.match(html, /id="outlookCalendarTitle"[\s\S]*id="showGoogleCalendar"[\s\S]*id="showOutlookCalendar"[\s\S]*id="connectOutlookCalendar"[\s\S]*id="calendarPreviousMonth"[\s\S]*id="calendarToday"[\s\S]*id="calendarNextMonth"[\s\S]*id="outlookCalendarList"/, "Ana Sayfada Google ve Outlook sağlayıcılarını destekleyen aylık takvim bulunmalı");
assert.match(outlookCalendarClient, /SCOPES\s*=\s*\["Calendars\.ReadBasic"\]/, "Outlook Takvim yalnızca en düşük salt okunur takvim iznini istemeli");
assert.match(outlookCalendarClient, /createStandardPublicClientApplication[\s\S]*cacheLocation:\s*"sessionStorage"[\s\S]*handleRedirectPromise/, "Outlook OAuth akışı PKCE destekli MSAL SPA istemcisi kullanmalı");
assert.match(outlookCalendarClient, /startDateTime[\s\S]*endDateTime[\s\S]*graph\.microsoft\.com\/v1\.0\/me\/calendar\/calendarView/, "Outlook etkinlikleri Microsoft Graph calendarView üzerinden tarih aralığıyla alınmalı");
assert.doesNotMatch(outlookCalendarClient, /clientSecret|CLIENT_SECRET/, "Microsoft client secret tarayıcı kodunda bulunmamalı");
assert.match(googleCalendarClient, /SCOPES\s*=\s*\["https:\/\/www\.googleapis\.com\/auth\/calendar\.events\.readonly"\]/, "Google Takvim yalnızca etkinlikleri okumaya yönelik izni istemeli");
assert.match(googleCalendarClient, /initTokenClient[\s\S]*include_granted_scopes:\s*true[\s\S]*requestAccessToken/, "Google Takvim GIS token modeliyle yetkilendirilmeli");
assert.match(googleCalendarClient, /singleEvents:\s*"true"[\s\S]*orderBy:\s*"startTime"[\s\S]*calendar\/v3\/calendars\/primary\/events/, "Google etkinlikleri primary takvimden tarih sırasıyla alınmalı");
assert.doesNotMatch(googleCalendarClient, /clientSecret|CLIENT_SECRET/, "Google client secret tarayıcı kodunda bulunmamalı");
assert.match(app, /function normalizeCalendarEvent[\s\S]*function renderCalendar[\s\S]*calendar-weekday-row[\s\S]*calendar-day-cell[\s\S]*calendar-event-chip[\s\S]*event\.subject/, "Google ve Outlook etkinlikleri ortak aylık takvim hücrelerinde gösterilmeli");
assert.match(app, /function updateCalendarPeriod[\s\S]*leadingDays[\s\S]*addDays\(start, 42\)[\s\S]*function changeCalendarMonth[\s\S]*calendarPreviousMonth[\s\S]*calendarToday[\s\S]*calendarNextMonth/, "Aylık takvim altı haftalık görünüm ve aylar arası gezinme sağlamalı");
assert.match(css, /calendar-weekday-row,\s*\.calendar-date-grid[^{]*\{[^}]*grid-template-columns:\s*repeat\(7[\s\S]*calendar-day-cell\.is-today/, "Takvim yedi sütunlu ay şablonu ve bugün vurgusu kullanmalı");
assert.match(css, /calendar-day-cell[^{]*\{[^}]*height:\s*46px[\s\S]*calendar-event-chip small[^{]*\{[^}]*display:\s*none/, "Aylık takvim Windows takvimi benzeri kompakt hücre ve tek satırlık etkinlik düzeni kullanmalı");
assert.match(app, /function selectCalendarProvider[\s\S]*CALENDAR_PROVIDER_KEY[\s\S]*function initializeCalendar[\s\S]*OutlookCalendar\.initialize/, "Takvim sağlayıcısı seçilebilmeli ve Outlook oturumu gerektiğinde geri yüklenmeli");
assert.match(app, /reminderForm\.addEventListener\("submit"[\s\S]*ReminderStore\.(?:update|create)/, "Not ve hatırlatma formu CRUD akışına bağlanmalı");
assert.match(reminders, /function validate[\s\S]*function replaceAll/, "Hatırlatma veri modeli doğrulama ve yedek geri yükleme sağlamalı");
const homeSummaryStart = html.indexOf('class="home-summary-panel"');
const homeWidgetsStart = html.indexOf('class="home-top-widgets"');
assert.ok(homeSummaryStart < html.indexOf('class="home-kpi-grid"') && html.indexOf('class="home-kpi-grid"') < homeWidgetsStart, "Çalışma özeti ve haftalık göstergeler tek üst bölümde birleştirilmeli");
assert.doesNotMatch(html.slice(homeSummaryStart, homeWidgetsStart), />\+ Efor ekle<\/button>/, "Çalışma özeti bölümünde Efor ekle düğmesi bulunmamalı");
assert.match(html.slice(homeSummaryStart, homeWidgetsStart), /class="home-kpi-card home-kpi-primary"[^>]*data-home-target="effortsView"[\s\S]*class="home-kpi-card"[^>]*data-home-target="effortsView"[\s\S]*class="home-kpi-card"[^>]*data-home-target="tasksView"[\s\S]*class="home-kpi-card"[^>]*data-home-target="tasksView"/, "Çalışma özeti kartları ilgili Eforlar ve Görevler bölümlerine bağlanmalı");
assert.match(css, /home-kpi-card:hover[^{]*\{[^}]*transform:\s*translateY/, "Tıklanabilir çalışma özeti kartları hover geri bildirimi vermeli");
assert.match(app, /data-home-target[\s\S]*targetView[\s\S]*activateMainView\(targetView\)[\s\S]*targetView === "tasksView"[\s\S]*activateTaskSubview\("taskReportView"\)/, "Görev özet kartları Görevler rapor sayfasını açmalı");
assert.ok(html.indexOf('class="panel home-quick-reminder"') < html.indexOf('class="home-dashboard-grid"'), "Önemli Notlar ve Hatırlatmalar Ana Sayfanın üst kısmında olmalı");
assert.ok(html.indexOf('class="home-top-widgets"') < html.indexOf('class="panel outlook-calendar-dashboard"') && html.indexOf('class="panel outlook-calendar-dashboard"') < html.indexOf('class="panel home-quick-reminder"'), "Outlook Takvim solda, Önemli Notlar ve Hatırlatmalar sağda aynı üst bölümde olmalı");
assert.match(css, /home-top-widgets[^{]*\{[^}]*display:\s*grid[^}]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/, "Takvim ve hatırlatma kutuları masaüstünde eşit genişlikte yerleşmeli");
assert.match(css, /home-top-widgets[^{]*\{[^}]*align-items:\s*stretch/, "Takvim ve hatırlatma kutularının yükseklikleri eşit olmalı");
assert.match(css, /@media\s*\(max-width:\s*850px\)[\s\S]*home-top-widgets[^{]*\{[^}]*grid-template-columns:\s*1fr/, "Takvim ve hatırlatma kutuları dar ekranda alt alta geçmeli");
assert.match(html, /id="openReminderModal"[\s\S]*id="reminderTickerWindow"[\s\S]*id="reminderModal"[\s\S]*id="reminderForm"/, "Hatırlatma ekleme formu Ana Sayfayı kaplamadan popup içinde açılmalı");
assert.match(app, /openReminderModal"\)\.addEventListener\("click", openReminderCreateModal\)/, "Hatırlatma ekle düğmesi popup formunu açmalı");
assert.match(app, /classList\.toggle\("is-ticker", reminders\.length > 1\)[\s\S]*cloneNode\(true\)/, "Hatırlatmalar kesintisiz kayan akış için çoğaltılmalı");
assert.match(css, /reminder-ticker-window[^{]*\{[^}]*height:\s*76px[\s\S]*@keyframes reminder-flow[^{]*\{[^}]*translateY/, "Hatırlatma kutusu kompakt olmalı ve aşağıdan yukarı akmalı");
assert.match(app, /weeklyEntries[\s\S]*homeWeeklyHours[\s\S]*homeWeeklyEntryCount/, "Haftalık efor özeti eksik");
assert.match(html, /data-effort-chart-period="week"[\s\S]*data-effort-chart-period="month"[\s\S]*data-effort-chart-period="year"/, "Efor dağılımı grafiğinde haftalık, aylık ve yıllık dönem seçenekleri bulunmalı");
assert.match(app, /function buildHomeEffortChartModel[\s\S]*period === "year"[\s\S]*length:\s*12|function buildHomeEffortChartModel[\s\S]*Array\.from\(\{ length: 12 \}/, "Yıllık efor görünümü 12 aylık dağılım üretmeli");
assert.match(app, /monthMode[\s\S]*getDate\(\)[\s\S]*minimumMaximum:\s*8/, "Aylık efor görünümü ayın günlerine göre dağılım üretmeli");
assert.match(app, /data-effort-chart-period[\s\S]*homeEffortChartPeriod[\s\S]*renderHomeDashboard\(\)/, "Efor grafiği dönem seçimi grafiği yeniden oluşturmalı");
assert.match(css, /weekly-effort-chart\[data-period="month"\][\s\S]*weekly-effort-chart\[data-period="year"\]/, "Aylık ve yıllık efor grafikleri için duyarlı kolon boyutları bulunmalı");
assert.match(app, /function formatEffortDays|const formatEffortDays[\s\S]*\/ 8/, "Efor gün karşılığı 8 saat üzerinden hesaplanmalı");
assert.match(app, /formatRoundedHours[\s\S]*Math\.round/, "Efor istatistiklerinde saat küsuratları gösterilmemeli");
assert.match(html, /<strong id="effortWeekDays">[\s\S]*<small id="effortWeekHours">/, "Eforlar ekranında gün sayısı saat detayından daha görünür olmalı");
assert.match(app, /hours-badge"\)\.textContent = formatEffortDays\(entry\.hours\)[\s\S]*Süre: \$\{formatRoundedHours\(entry\.hours\)\}/, "Efor geçmişinde gün karşılığı öne çıkmalı, küsuratsız saat açıklama detayı olarak gösterilmeli");
assert.match(app, /weekTotal[\s\S]*monthTotal[\s\S]*effortWeekHours[\s\S]*effortMonthHours[\s\S]*effortTotalDays/, "Eforlar ekranı haftalık, aylık ve toplam istatistikleri saat ve gün bazında göstermeli");
assert.match(html, /id="addTimesheetEffort"[^>]*>\+ Efor ekle<\/button>/, "Yeni efor yalnızca Timesheet üzerinden açılabilmeli");
assert.doesNotMatch(html, /data-home-target="effortsView"[^>]*>\+ Efor ekle<\/button>/, "Ana Sayfadaki efor ekleme kısayolu Timesheet dışındaki bir ekleme ekranına gitmemeli");
assert.match(app, /addTimesheetEffort"\)\.addEventListener\("click"[\s\S]*openEffortCreateModal/, "Timesheet efor ekleme düğmesi popup formunu açmalı");
assert.match(app, /edit-button"\)\.addEventListener\("click", \(\) => openEffortEditModal\(\[entry\]\)\)/, "Efor geçmişindeki düzenleme işlemi popup açmalı");
assert.match(html, /class="panel form-panel hidden"[^>]*aria-hidden="true"/, "Eski Eforlar ekleme formu arayüzde görünmemeli");
assert.match(app, /plannedTasks[\s\S]*inProgressTasks[\s\S]*completedTasks/, "Görev durum özeti eksik");
assert.match(app, /weekly-bar-column[\s\S]*task-donut[\s\S]*jira-effort-row/, "Dashboard grafikleri eksik");
assert.match(app, /renderTimesheet\(\);\s*renderHomeDashboard\(\);/, "Efor render sonrası Ana Sayfa güncellenmeli");
assert.match(app, /function renderTasks[\s\S]*renderHomeDashboard\(\);\s*\}/, "Görev render sonrası Ana Sayfa güncellenmeli");
assert.match(css, /home-dashboard-grid[^{]*\{[^}]*grid-template-columns/, "Ana Sayfa responsive grid yapısı eksik");
assert.doesNotMatch(html, /id="projectInput"/, "Efor formunda bağımsız proje alanı olmamalı");
assert.match(html, /id="descriptionInput"[^>]*maxlength="1000"/, "Ana efor açıklaması 1000 karakter desteklemeli");
assert.match(html, /id="modalDescriptionInput"[^>]*maxlength="1000"/, "Timesheet efor açıklaması 1000 karakter desteklemeli");
assert.match(html, /descriptionCount">0<\/span>\/1000 karakter/, "Efor açıklaması karakter sayacı 1000 limitini göstermeli");
assert.match(html, /id="jiraItemInput"[^>]*required/, "Efor formunda JIRA seçimi zorunlu olmalı");
assert.match(html, /id="jiraItemPickerButton"[^>]*aria-haspopup="listbox"[^>]*aria-controls="jiraItemPickerDropdown"/, "Efor JIRA seçimi erişilebilir bir açılır liste olmalı");
assert.match(html, /id="jiraItemPickerDropdown" class="jira-picker-dropdown hidden"[\s\S]*id="jiraItemSearchInput"[^>]*type="search"[^>]*aria-controls="jiraItemOptionList"/, "Efor JIRA araması açılır listenin içinde yer almalı");
assert.match(app, /function normalizeJiraSearch[\s\S]*toLocaleLowerCase\("tr-TR"\)[\s\S]*replaceAll\("ı", "i"\)/, "Efor JIRA araması büyük-küçük harf ve Türkçe I karakterlerinden etkilenmemeli");
assert.match(app, /function jiraMatchesSearch[\s\S]*item\.name[\s\S]*item\.description[\s\S]*item\.assignee[\s\S]*item\.status/, "Efor JIRA araması Key, Summary, kişi ve durum alanlarını filtrelemeli");
assert.match(app, /jiraItemSearchInput"\)\.addEventListener\("input"[\s\S]*scheduleIntegratedJiraSearch\("main"\)/, "Efor JIRA seçenekleri kullanıcı yazarken anlık filtrelenmeli");
assert.match(app, /function renderIntegratedJiraOptionList[\s\S]*jira-picker-option[\s\S]*aria-selected/, "Filtrelenen ve canlı JIRA maddeleri açılır listede seçilebilir gösterilmeli");
assert.match(app, /function setIntegratedJiraPickerOpen[\s\S]*aria-expanded[\s\S]*dropdown\.classList\.toggle[\s\S]*function setEffortJiraPickerOpen/, "JIRA açılır listelerinin açık-kapalı durumu yönetilmeli");
assert.match(html, /id="modalJiraPicker"[\s\S]*id="modalJiraSearchInput"[\s\S]*id="modalJiraOptionList"[\s\S]*id="modalJiraInput"/, "Timesheet efor penceresinde aramalı JIRA seçici bulunmalı");
assert.match(app, /async function searchIntegratedJiraIssues[\s\S]*search\.length < 2[\s\S]*JiraCloudClient\.searchIssues/, "Efor JIRA seçicileri iki karakterden sonra canlı JIRA önerisi aramalı");
assert.match(app, /async function selectRemoteJiraIssue[\s\S]*JiraCloudClient\.getIssue[\s\S]*JiraStore\.mergeAll[\s\S]*waitForDataSaves/, "Canlı sonuçtan seçilen JIRA maddesi tam bilgilerle Supabase'e kaydedilmeli");
assert.match(app, /project:\s*selectedJira\.name/, "Eforun proje karşılığı seçilen JIRA anahtarından türetilmeli");
assert.ok(html.indexOf('src="jira-cloud.js') < html.indexOf('src="app.js'), "JIRA Cloud istemcisi uygulamadan önce yüklenmeli");
assert.doesNotMatch(jiraCloudClient, /JIRA_API_TOKEN|Authorization:\s*`Basic/, "JIRA API token tarayıcı kodunda bulunmamalı");
assert.match(jiraCloudClient, /credentials:\s*"include"/, "JIRA OAuth oturum çerezi backend isteklerinde güvenli biçimde gönderilmeli");
assert.match(jiraCloudClient, /function getOAuthStatus[\s\S]*\/oauth\/status[\s\S]*function getOAuthStartUrl[\s\S]*\/oauth\/start[\s\S]*function signOutFromJira[\s\S]*\/oauth\/logout/, "JIRA istemcisi giriş durumu, yönlendirme ve çıkış akışlarını desteklemeli");
assert.match(aiServer, /process\.env\.JIRA_API_TOKEN[\s\S]*Basic \$\{Buffer\.from/, "JIRA API token yalnızca backend kimlik doğrulamasında kullanılmalı");
assert.match(aiServer, /JIRA_OAUTH_CLIENT_ID[\s\S]*JIRA_OAUTH_CLIENT_SECRET[\s\S]*JIRA_OAUTH_REDIRECT_URI/, "JIRA OAuth sırları yalnızca backend ortam ayarlarından okunmalı");
assert.match(aiServer, /\/api\/jira\/oauth\/start[\s\S]*crypto\.randomBytes[\s\S]*auth\.atlassian\.com\/authorize[\s\S]*state[\s\S]*prompt:\s*"consent"/, "JIRA OAuth başlangıcı tahmin edilemez state ve Atlassian consent yönlendirmesi kullanmalı");
assert.match(aiServer, /auth\.atlassian\.com\/oauth\/token[\s\S]*grant_type:\s*"refresh_token"[\s\S]*session\.refreshToken = token\.refresh_token/, "JIRA rotating refresh token her yenilemede güvenli biçimde değiştirilmelidir");
assert.match(aiServer, /oauth\/token\/accessible-resources/, "JIRA OAuth yetkilendirilen siteleri accessible-resources üzerinden almalı");
assert.match(aiServer, /api\.atlassian\.com\/ex\/jira\/\$\{encodeURIComponent\(session\.cloudId\)\}/, "JIRA OAuth API çağrıları yetkilendirilen cloudId üzerinden yapılmalı");
assert.match(aiServer, /JIRA_SESSION_COOKIE[\s\S]*HttpOnly[\s\S]*SameSite=None[\s\S]*Secure/, "JIRA OAuth oturumu HttpOnly ve HTTPS üzerinde cross-site güvenli çerez kullanmalı");
assert.doesNotMatch(jiraCloudClient, /client_secret|JIRA_OAUTH_CLIENT_SECRET|access_token|refresh_token/, "JIRA OAuth sırları ve tokenları frontend kodunda bulunmamalı");
assert.match(supabaseCloudClient, /async function invokeJira[\s\S]*functions\.invoke\("jira-proxy"[\s\S]*getSession/, "GitHub Pages JIRA istekleri Supabase oturumuyla Edge Function'a gönderilmeli");
assert.match(jiraCloudClient, /supabase:jira-proxy[\s\S]*SupabaseCloud\.invokeJira[\s\S]*function saveCredentials[\s\S]*function removeCredentials/, "JIRA istemcisi Supabase proxy ve kullanıcı bağlantı bakımını desteklemeli");
assert.match(jiraCloudClient, /githubPages[\s\S]*saved\.startsWith\("\/"\)[\s\S]*supabase:jira-proxy/, "GitHub Pages'teki eski göreli backend ayarı otomatik olarak Supabase proxy'ye taşınmalı");
assert.match(jiraEdgeFunction, /admin\.auth\.getUser\(token\)[\s\S]*get_jira_credentials[\s\S]*save_jira_credentials[\s\S]*delete_jira_credentials/, "JIRA Edge Function Supabase kullanıcısını doğrulayıp kişisel bağlantıyı güvenli RPC üzerinden yönetmeli");
assert.match(jiraEdgeFunction, /Authorization:\s*`Basic[\s\S]*\/rest\/api\/3\/search\/jql[\s\S]*\/worklog/, "JIRA Edge Function issue ve worklog işlemlerini sunucu tarafında gerçekleştirmeli");
assert.doesNotMatch(jiraEdgeFunction, /ATATT|sb_secret_[A-Za-z0-9_-]+|JIRA_API_TOKEN\s*=/, "Edge Function kaynak kodunda gerçek bir JIRA veya Supabase sırrı bulunmamalı");
assert.match(jiraVaultMigration, /private\.jira_credentials[\s\S]*vault\.create_secret[\s\S]*vault\.decrypted_secrets[\s\S]*revoke all[\s\S]*service_role/, "JIRA tokenı Vault'ta şifreli tutulmalı ve yalnızca service_role RPC erişimine açık olmalı");
assert.match(app, /async function saveJiraCredentials[\s\S]*JiraCloudClient\.saveCredentials[\s\S]*async function removeJiraCredentials[\s\S]*JiraCloudClient\.removeCredentials/, "JIRA bağlantı bilgileri uygulamadan kaydedilip kaldırılabilmeli");
assert.match(html, /id="getJiraApiToken"[\s\S]*href="https:\/\/id\.atlassian\.com\/manage-profile\/security\/api-tokens"[\s\S]*target="_blank"[\s\S]*rel="noopener noreferrer"/, "JIRA bağlantı ayarları resmi Atlassian API token sayfasını güvenli biçimde açmalı");
assert.match(html, /class="header-utility-nav"[\s\S]*id="supabaseHeaderMenu"[\s\S]*id="driveHeaderMenu"[\s\S]*id="jiraHeaderMenu"[\s\S]*id="jiraCredentialTitle"[\s\S]*id="jiraSyncJql"[\s\S]*id="jiraAutoWorklog"/, "JIRA bağlantı ve senkronizasyon ayarları Bulut hesabı ile Yedekleme yanındaki ana menüde bulunmalı");
assert.doesNotMatch(html, /id="jiraApiEndpoint"|id="saveJiraApiEndpoint"|JIRA servis yöntemi|Adresi kaydet/, "Kullanıcının JIRA servis adresini elle yönetmesine gerek kalmamalı");
assert.match(app, /function refreshJiraHeaderMenu[\s\S]*headerJiraMenuLabel[\s\S]*is-connected[\s\S]*Ayarlar aktif/, "JIRA ana menüsü etkin bağlantıyı yeşil durumla göstermeli");
assert.match(css, /header-jira-menu\.is-connected[^{]*\{[^}]*background:\s*#1f9d74[\s\S]*jira-header-popover/, "Bağlı JIRA menüsü yeşil görünmeli ve ayarlar açılır pencerede yer almalı");
assert.match(app, /function renderJiraOAuthState[\s\S]*jiraOAuthBadge[\s\S]*connectJiraOAuth[\s\S]*disconnectJiraOAuth/, "JIRA OAuth bağlantı durumu arayüzde gösterilmeli");
assert.match(app, /connectJiraOAuth"\)\.addEventListener\("click"[\s\S]*signInWithJira[\s\S]*disconnectJiraOAuth"\)\.addEventListener\("click"[\s\S]*signOutFromJira/, "JIRA giriş ve çıkış düğmeleri OAuth istemcisine bağlanmalı");
assert.match(aiServer, /\/rest\/api\/3\/search\/jql[\s\S]*mapJiraIssue/, "Backend JQL ile JIRA maddelerini senkronize etmeli");
assert.match(aiServer, /singleJiraIssueMatch[\s\S]*\/rest\/api\/3\/issue\/\$\{encodeURIComponent\(issueKey\)\}\?fields=[\s\S]*mapJiraIssue/, "Backend tek bir JIRA Key ile tüm issue alanlarını almalı");
assert.match(jiraCloudClient, /function getIssue\(issueKey\)[\s\S]*request\(`\/issues\/\$\{encodeURIComponent\(key\)\}`/, "JIRA istemcisi Key ile tekil madde sorgulamalı");
assert.match(jiraCloudClient, /function transitionIssue\(issueKey, targetStatus\)[\s\S]*\/transitions[\s\S]*method:\s*"POST"/, "JIRA istemcisi issue statü transition işlemini desteklemeli");
assert.match(app, /function fetchJiraIssueByKey[\s\S]*JiraCloudClient\.getIssue\(key\)[\s\S]*JiraStore\.mergeAll/, "JIRA ekleme formu yalnızca Key ile JIRA Cloud'dan veri çekip birleştirmeli");
assert.match(html, /id="jiraForm"[\s\S]*id="jiraNameInput"[^>]*pattern="\[A-Za-z\]\[A-Za-z0-9_\]\*-\[0-9\]\+"[\s\S]*id="jiraSubmitButton"/, "JIRA formu yalnızca Key sorgusu içermeli");
assert.doesNotMatch(html, /id="jira(?:Description|Url|IssueType|Assignee|Reporter|Priority|Status|Resolution|Created|Updated|DueDate)Input"/, "JIRA formunda elle doldurulan detay alanları bulunmamalı");
assert.match(aiServer, /\/rest\/api\/3\/issue\/\$\{encodeURIComponent\(issueKey\)\}\/worklog/, "Backend JIRA worklog API'sine bağlanmalı");
assert.match(aiServer, /jiraTransitionMatch[\s\S]*\/transitions[\s\S]*transition:\s*\{\s*id:[\s\S]*mapJiraIssue/, "Backend hedef statüye uygun JIRA transition işlemini uygulamalı");
assert.match(aiServer, /worklogAuthor = currentUser\(\)[\s\S]*startedAfter[\s\S]*mapped\.authorAccountId === account\.accountId/, "Backend seçili tarih aralığında yalnızca oturum kullanıcısının JIRA workloglarını almalı");
assert.match(jiraCloudClient, /function syncWorklogs\(from, to\)[\s\S]*request\(`\/worklogs\?\$\{params\}`/, "JIRA istemcisi tarih aralığıyla worklog senkronizasyonunu desteklemeli");
assert.match(app, /function syncTimesheetJiraWorklogs[\s\S]*mergeJiraWorklogs[\s\S]*JIRA’dan alınan eforlar Drive’a gönderildi/, "Timesheet JIRA eforlarını mükerrer oluşturmadan yerel veriye ve Drive yedeğine aktarmalı");
assert.match(dataStore, /function mergeJiraWorklogs[\s\S]*byWorklogId[\s\S]*conflicts/, "JIRA worklog kimliğiyle mükerrer ve yerel değişiklik çakışmaları yönetilmeli");
assert.match(app, /function syncJiraCloudIssues[\s\S]*JiraStore\.mergeAll/, "Canlı JIRA senkronizasyonu mevcut Key kayıtlarını birleştirmeli");
assert.match(app, /JIRA_WORKLOGGED_ISSUES_JQL\s*=\s*"worklogAuthor = currentUser\(\) ORDER BY updated DESC"[\s\S]*function refreshJiraNavigatorFromWorklogs[\s\S]*syncJiraCloudIssues/, "JIRA Issue Navigator worklog girilen maddeleri açılışta yenilemeli");
assert.match(app, /function activateMainView[\s\S]*activateJiraSubview\("jiraItemsView"\)[\s\S]*function activateJiraSubview[\s\S]*refreshJiraNavigatorFromWorklogs/, "JIRA Maddeleri sekmesine geçildiğinde otomatik worklog maddesi senkronizasyonu başlamalı");
assert.match(app, /function renderJiraSelectionControls[\s\S]*selectedJiraItemIds[\s\S]*function deleteSelectedJiraItems[\s\S]*JiraStore\.removeMany/, "JIRA Issue Navigator seçme, seçimi bırakma ve toplu silme işlemlerini desteklemeli");
assert.match(html, /id="refreshJiraNavigator"[\s\S]*id="selectAllJiraItems"[\s\S]*id="clearJiraItemSelection"[\s\S]*id="deleteSelectedJiraItems"[\s\S]*class="jira-row-select"/, "JIRA listesinde yenileme ve toplu seçim kontrolleri bulunmalı");
assert.match(jira, /function removeMany[\s\S]*selected[\s\S]*removed/, "JIRA veri katmanı toplu silmeyi tek kayıt işlemiyle desteklemeli");
assert.match(html, /class="jira-subtab-button active"[^>]*data-jira-tab="jiraItemsView"[\s\S]*data-jira-tab="jiraRequestsView"/, "JIRA ekranında JIRA Maddeleri ve Talepler alt sekmeleri bulunmalı");
assert.match(app, /function activateJiraSubview[\s\S]*jira-subtab-button[\s\S]*jira-subview/, "JIRA alt sekme geçişleri bağlanmalı");
assert.match(app, /function groupJiraRequestsByStatus[\s\S]*item\.status[\s\S]*function renderJiraRequests[\s\S]*jira-request-column/, "Talepler JIRA statüsüne göre Kanban sütunlarında gruplanmalı");
assert.match(app, /function renderJiraRequestStatusFilters[\s\S]*selectedJiraRequestStatuses[\s\S]*checkbox[\s\S]*renderJiraRequests/, "Talepler görünümünde çoklu statü seçimi bulunmalı");
assert.match(app, /selectAllJiraRequestStatuses[\s\S]*selectedJiraRequestStatuses\.add[\s\S]*clearJiraRequestStatuses[\s\S]*selectedJiraRequestStatuses\.clear/, "Tüm statüleri seçme ve temizleme işlemleri bağlanmalı");
assert.match(app, /function transitionJiraRequest[\s\S]*JiraCloudClient\.transitionIssue[\s\S]*JiraStore\.update\(previousItem\.id, previousItem\)/, "Kanban statü geçişi JIRA'ya gönderilmeli ve hatada yerel statü geri alınmalı");
assert.match(app, /function transitionJiraRequest[\s\S]*confirm\([\s\S]*JIRA’ya gönderilsin mi[\s\S]*if \(!approved\)[\s\S]*statü değişikliği iptal edildi/, "Kanban statü değişikliği JIRA'ya gönderilmeden önce kullanıcı onayı istemeli");
assert.match(app, /column\.addEventListener\("dragover"[\s\S]*column\.addEventListener\("drop"[\s\S]*card\.draggable[\s\S]*dragstart/, "Talep kartları statü sütunları arasında sürüklenip bırakılabilmeli");
assert.match(app, /jiraRequestsSearch[\s\S]*renderJiraRequests/, "Talepler görünümünde anlık arama bulunmalı");
assert.match(html, /id="jiraItemsView"[\s\S]*JIRA issue navigator[\s\S]*id="jiraAssigneeFilterPicker"[\s\S]*id="jiraAssigneeFilterSearch"[\s\S]*id="jiraAssigneeFilterOptions"[\s\S]*id="clearJiraAssigneeFilter"/, "Canlı kullanıcı filtresi JIRA Issue Navigator araçlarının içinde bulunmalı");
assert.match(html, /id="jiraRequestsView"[\s\S]*id="jiraRequestsAssigneeFilterPicker"[\s\S]*id="jiraRequestsAssigneeFilterSearch"[\s\S]*id="jiraRequestsAssigneeFilterOptions"[\s\S]*id="clearJiraRequestsAssigneeFilter"/, "Talepler görünümünde aynı atanan kullanıcı filtresi bulunmalı");
assert.match(app, /async function searchJiraAssigneeFilters[\s\S]*search\.length < 2[\s\S]*JiraCloudClient\.searchUsers/, "JIRA kullanıcı filtresi yazarken canlı Atlassian kullanıcılarını aramalı");
assert.match(app, /function jiraItemMatchesAssigneeFilter[\s\S]*assigneeAccountId[\s\S]*normalizePersonName/, "JIRA kullanıcı filtresi Account ID ve eski kayıtlar için görünen adla eşleşmeli");
assert.match(app, /function refreshSelectedJiraAssigneeIssues[\s\S]*jiraAssigneeFilterJql[\s\S]*syncJiraCloudIssues/, "Seçilen kullanıcıya atanmış maddeler JIRA'dan canlı senkronize edilmeli");
assert.match(app, /function filteredJiraItems[\s\S]*jiraItemMatchesAssigneeFilter[\s\S]*function renderJiraRequests[\s\S]*filter\(jiraItemMatchesAssigneeFilter\)/, "Kullanıcı filtresi hem JIRA tablosuna hem Talepler Kanban'ına uygulanmalı");
assert.match(css, /jira-assignee-filter-control[^{]*\{[^}]*z-index:\s*20[\s\S]*jira-list-panel,\s*\.jira-requests-panel[^{]*\{[^}]*overflow:\s*visible/, "JIRA kullanıcı filtreleri ilgili panelin içinde görünür bir açılır katman kullanmalı");
assert.match(jira, /assigneeAccountId:[\s\S]*optionalLimits[\s\S]*assigneeAccountId/, "JIRA veri modeli atanan kişinin Account ID bilgisini korumalı");
assert.match(aiServer, /assigneeAccountId:\s*String\(fields\.assignee\?\.accountId/, "Yerel JIRA proxy atanan kişinin Account ID bilgisini dönmeli");
assert.match(jiraEdgeFunction, /assigneeAccountId:\s*String\(fields\.assignee\?\.accountId/, "Supabase JIRA proxy atanan kişinin Account ID bilgisini dönmeli");
assert.match(css, /jira-subtabs[\s\S]*jira-request-status-filters[\s\S]*jira-request-board[\s\S]*grid-auto-flow:\s*column[\s\S]*jira-request-column\.is-drop-target[\s\S]*jira-request-card\.is-dragging/, "Talepler Kanban'ında sürükleme hedefi ve taşınan kart stillendirilmeli");
assert.match(app, /function syncEffortToJira[\s\S]*updateWorklog[\s\S]*createWorklog/, "Efor kaydı JIRA worklog oluşturma ve güncelleme akışına bağlanmalı");
assert.match(app, /function syncEffortToJira[\s\S]*approvalMessage[\s\S]*confirm\(approvalMessage\)[\s\S]*approvalDeclined/, "JIRA worklog kullanıcı onayı olmadan gönderilmemeli");
assert.match(app, /bağlı JIRA worklog da silinsin mi[\s\S]*deleteWorklog/, "JIRA worklog silme işlemi ayrıca kullanıcı onayı istemeli");
assert.match(html, /class="jira-worklog-status hidden"/, "Efor geçmişi JIRA worklog durumunu göstermeli");
assert.match(app, /jira-worklog-status-icon[\s\S]*synced:\s*"✓"[\s\S]*JIRA’ya gönderildi/, "Başarılı JIRA worklog kaydı yeşil onay simgesiyle belirtilmeli");
assert.match(css, /jira-worklog-status\[data-status="synced"\][\s\S]*jira-worklog-status-icon[^{]*\{[^}]*background:\s*#1f9d74/, "Başarılı JIRA simgesi yeşil görünmeli");
assert.match(app, /function sanitizeTaskHtml/, "Görev HTML açıklaması güvenli biçimde temizlenmeli");
assert.match(taskDetailApp, /description\.innerHTML\s*=\s*sanitizeTaskHtml\(task\.descriptionHtml\)/, "Görev HTML açıklaması ayrı detay sayfasında yalnızca temizlenerek gösterilmeli");
assert.match(app, /blockedTags.*SCRIPT.*IFRAME.*OBJECT/s, "Tehlikeli HTML etiketleri engellenmeli");
assert.match(html, /data-task-command="bold"[\s\S]*data-task-command="insertUnorderedList"/, "Görev HTML biçimlendirme araçları eksik");
assert.match(app, /function applyTaskEditorCommand[\s\S]*button\.dataset\.taskCommand/, "Görev HTML araç çubuğu komutları bağlanmalı");
assert.match(html, /data-task-tab="taskCreateView"[\s\S]*data-task-tab="taskReportView"/, "Görev Ekle ve Yapılacak İşler alt sekmeleri eksik");
assert.match(html, /class="task-subtab-button active"[^>]*data-task-tab="taskReportView"/, "Görevler ilk açıldığında görev raporu görünmeli");
assert.match(html, /id="taskReportView" class="panel task-subview task-list-panel"/, "Görev raporu başlangıçta açık olmalı");
assert.match(html, /id="taskTypeFilter"[\s\S]*value="" selected[\s\S]*value="architecture_roadmap"/, "Görev raporu tüm görev tipi gruplarıyla açılmalı");
assert.match(html, /taskTypeGroupTemplate[\s\S]*task-type-group-total[\s\S]*data-priority="high"[\s\S]*data-priority="medium"[\s\S]*data-priority="low"[\s\S]*data-priority="none"/, "Görev tipi grup satırı toplam ve öncelik sayaçlarını içermeli");
assert.match(app, /function groupTasksByType[\s\S]*priorities:[\s\S]*high:[\s\S]*medium:[\s\S]*low:[\s\S]*none:/, "Görevler tip bazında toplam ve öncelik sayılarına göre gruplanmalı");
assert.match(app, /task-type-group-toggle[\s\S]*new URLSearchParams\(\{ type: group\.taskType \}\)[\s\S]*task-type-report\.html\?\$\{params\}/, "Görev tipi başlığı ayrı rapor sayfasına yönlenmeli");
assert.match(css, /task-type-priority-count\[data-priority="high"\][\s\S]*task-type-priority-count\[data-priority="medium"\][\s\S]*task-type-priority-count\[data-priority="low"\]/, "Öncelik sayaçları farklı renklerle gösterilmeli");
assert.doesNotMatch(app, /replaceLocalBundle[\s\S]*migrateExistingTasksToArchitectureRoadmap\(\)[\s\S]*async function pullFromSupabase/, "Buluttan yüklenen görevlerin tipi sayfa yenilemesinde değiştirilmemeli");
assert.match(html, /task-report-table[\s\S]*<thead><tr><th>Görev<\/th><th class="task-status-column">Durum<\/th><\/tr><\/thead>/, "Yapılacak İşler raporunda yalnızca Görev ve Durum başlıkları olmalı");
assert.doesNotMatch(html, /<thead><tr><th>Görev<\/th><th class="task-status-column">Durum<\/th><th/, "Görev ve Durum dışında ana rapor sütunu bulunmamalı");
assert.match(taskDetailHtml, /task-detail-overview-table[\s\S]*Tamamlandı[\s\S]*Görev \/ Alt Görev[\s\S]*Bağlı Ana Görev[\s\S]*Atanan \/ Kimde Bekliyor[\s\S]*Öncelik[\s\S]*Yıl \/ Çeyrek[\s\S]*Teslim Tarihi[\s\S]*Durum[\s\S]*İşlemler/, "Eski rapor sütunlarının tamamı ayrı görev detay sayfasında gösterilmeli");
assert.match(taskTypeReportApp, /REPORT_COLUMNS[\s\S]*Tamamlandı[\s\S]*Görev \/ Alt Görev[\s\S]*Bağlı Ana Görev[\s\S]*Atanan \/ Kimde Bekliyor[\s\S]*Öncelik[\s\S]*Yıl \/ Çeyrek[\s\S]*Teslim Tarihi[\s\S]*Durum[\s\S]*İşlemler/, "Görev tipi raporu seçilebilir detay sütunlarının tamamını tanımlamalı");
assert.match(taskTypeReportApp, /function renderReportColumnOptions[\s\S]*checkbox[\s\S]*reportLayout\.visible[\s\S]*renderTaskTypeReport/, "Görev tipi raporu kolonları kullanıcı tarafından gösterilip gizlenebilmeli");
assert.match(taskTypeReportApp, /function applyReportFitMode[\s\S]*fitScreen[\s\S]*totalWeight[\s\S]*taskTypeReportFitToggle/, "Görev tipi raporu görünür kolonları ekrana orantılı sığdırmalı");
assert.match(taskTypeReportApp, /bundle\.settings\?\.taskTypeReportLayout/, "Görev tipi raporu kayıtlı kolon tercihini Supabase paketinden yüklemeli");
assert.match(taskTypeReportApp, /updateUserSettings\(\{ taskTypeReportLayout: reportLayout \}\)/, "Görev tipi raporu kolon tercihini Supabase kullanıcı ayarlarında saklamalı");
assert.match(css, /task-type-report-page \.task-detail-page-main[^{]*\{[^}]*1540px[\s\S]*task-type-report-table\.fit-screen[^{]*\{[^}]*table-layout:\s*fixed/, "Görev tipi detay raporu geniş ekranı kullanmalı ve tabloyu ekrana sığdırmalı");
assert.match(taskTypeReportApp, /TaskStore\.TASK_TYPES[\s\S]*filter\(\(task\)[\s\S]*task\.taskType[\s\S]*taskTypeReportBody/, "Görev tipi raporu yalnızca seçilen tipe ait maddeleri listelemeli");
assert.match(html, /taskPriorityInput[\s\S]*taskYearInput[\s\S]*taskQuarterInput/, "Görev formunda öncelik, yıl ve çeyrek alanları eksik");
assert.match(html, /taskTypeInput[\s\S]*meeting_organization[\s\S]*management_request/, "Görev tipi seçenekleri eksik");
assert.match(html, /taskTypeInput[\s\S]*architecture_roadmap/, "Architecture Roadmap görev tipi eksik");
assert.match(html, /id="taskAssigneePicker"[\s\S]*id="taskAssigneeSearchInput"[\s\S]*id="taskAssigneeOptionList"[\s\S]*id="taskAssigneeInput"[\s\S]*En az 2 karakter/, "Görev ataması canlı JIRA kullanıcı aramasına bağlanmalı");
assert.doesNotMatch(html, /<thead><tr>[\s\S]*?<th>Görev tipi<\/th>[\s\S]*?<\/tr><\/thead>/, "Görev tipi grup başlığında olduğu için rapor tablosunda yinelenmemeli");
assert.doesNotMatch(html, /id="taskDueDateInput"[^>]*required/, "Yıl ve çeyrek kullanılan görevlerde teslim tarihi zorunlu olmamalı");
assert.doesNotMatch(html, /<thead><tr>[^<]*(?:<th[^>]*>[^<]*<\/th>)*<th>Detaylı açıklama<\/th>/, "Görev raporunda detaylı açıklama sütunu olmamalı");
assert.match(app, /function activateTaskSubview[\s\S]*activateTaskSubview\("taskReportView"\)/, "Görev alt sayfa geçişleri bağlanmalı");
assert.match(app, /function showTaskDetail[\s\S]*task-detail\.html\?id=[\s\S]*encodeURIComponent\(task\.id\)/, "Görev başlığı ayrı detay sayfasına gitmeli");
assert.match(taskDetailApp, /URLSearchParams[\s\S]*TaskStore\.get[\s\S]*sanitizeTaskHtml/, "Ayrı görev detay sayfası görevi okuyup açıklamayı güvenli göstermeli");
assert.match(taskDetailApp, /detailPageRevise[\s\S]*editTask=[\s\S]*encodeURIComponent\(task\.id\)/, "Görev detayından revizyon bağlantısı eksik");
assert.match(taskDetailApp, /fromType[\s\S]*task-type-report\.html\?type=[\s\S]*taskDetailBackLink/, "Tekil görev detayından görev tipi raporuna dönüş bağlantısı eksik");
assert.match(app, /function applyInitialRoute[\s\S]*editTask[\s\S]*startTaskEdit/, "Revizyon bağlantısı görev formunu açmalı");
assert.match(app, /store\?\.create/, "Create entegrasyonu eksik");
assert.match(app, /store\?\.update/, "Update entegrasyonu eksik");
assert.match(app, /store\?\.remove/, "Delete entegrasyonu eksik");
assert.doesNotMatch(html, /class="icon-button calendar-button"/, "Takvim düğmesi efor satırlarında olmamalı");
assert.doesNotMatch(html, /calendar-dashboard-card|Yaklaşan görev|addNextTaskToCalendar|addNextTaskToOutlookCalendar/, "Efor özetinde yaklaşan görev takvim kartı bulunmamalı");
assert.doesNotMatch(app, /nextDashboardTask|googleCalendarUrl|outlookCalendarUrl/, "Kaldırılan yaklaşan görev kartının kullanılmayan uygulama kodu kalmamalı");
assert.ok(html.indexOf('src="drive-sync.js') < html.indexOf('src="app.js'), "Drive modülü uygulamadan önce yüklenmeli");
assert.ok(html.indexOf('src="tasks-store.js') < html.indexOf('src="app.js'), "Görev modülü uygulamadan önce yüklenmeli");
assert.ok(html.indexOf('src="people-store.js') < html.indexOf('src="app.js'), "Kişi modülü uygulamadan önce yüklenmeli");
assert.ok(html.indexOf('src="jira-store.js') < html.indexOf('src="app.js'), "JIRA modülü uygulamadan önce yüklenmeli");
assert.ok(html.indexOf('src="reminders-store.js') < html.indexOf('src="app.js'), "Hatırlatma modülü uygulamadan önce yüklenmeli");
assert.ok(html.indexOf('src="ai-assistant.js') < html.indexOf('src="app.js'), "AI istemci modülü uygulamadan önce yüklenmeli");
assert.match(html, /id="backupToDrive"/, "Drive yedekleme düğmesi eksik");
assert.match(html, /id="restoreFromDrive"/, "Drive geri yükleme düğmesi eksik");
assert.match(drive, /drive\.appdata/, "En az yetkili Drive kapsamı kullanılmalı");
assert.match(drive, /drive\.file/, "Göreve eklenen kullanıcı dosyaları için dar kapsamlı drive.file izni kullanılmalı");
assert.match(drive, /parents:\s*\["appDataFolder"\]/, "Yedek appDataFolder içine yazılmalı");
assert.match(drive, /uploadType=resumable[\s\S]*X-Upload-Content-Type[\s\S]*uploadTaskDocuments/, "Görev dokümanları Drive'a resumable upload ile gönderilmeli");
assert.match(drive, /application\/vnd\.google-apps\.folder[\s\S]*dailyEffortTrackerTaskId/, "Dokümanlar görev kimliğiyle işaretlenmiş ayrı Drive klasörlerinde tutulmalı");
assert.doesNotMatch(drive, /client_secret/i, "Client Secret tarayıcı kodunda bulunmamalı");
assert.match(tasks, /attachments:[\s\S]*normalizeAttachment[\s\S]*MAX_ATTACHMENTS/, "Görev veri modeli yalnızca normalize edilmiş doküman metadatasını saklamalı");
assert.match(app, /attachments:\s*taskExistingAttachments\.slice\(\)[\s\S]*uploadTaskDocuments[\s\S]*payload\.attachments\s*=\s*\[\.\.\.taskExistingAttachments,\s*\.\.\.uploaded\]/, "Görev formu seçilen dokümanları Drive'a yükleyip görevle ilişkilendirmeli");
assert.match(taskDetailApp, /safeDocumentUrl[\s\S]*task\.attachments[\s\S]*detailPageDocumentList/, "Görev detay sayfası Drive dokümanlarını güvenli bağlantılarla göstermeli");
assert.match(html, /class="drive-compact-panel"/, "Kompakt Drive yedekleme paneli eksik");
const pageHeaderEnd = html.indexOf("</header>");
const homeViewStart = html.indexOf('id="homeView"');
const mainMenuStart = html.indexOf('class="main-menu-bar"');
assert.ok(mainMenuStart > pageHeaderEnd && mainMenuStart < homeViewStart, "Ana navigasyon ve işlem menüleri üst başlığın altında yer almalı");
assert.ok(html.indexOf('id="driveHeaderMenu"') > pageHeaderEnd && html.indexOf('id="driveCompactPanel"') < homeViewStart, "Drive durumu, ayarları ve yedekleme işlemleri tek ana menü panelinde olmalı");
assert.match(css, /\.main-menu-bar\s*\{[^}]*display:\s*flex/, "Ana menü navigasyon ve işlem kontrollerini aynı satırda toplamalı");
assert.match(css, /\.header-menu-popover\s*\{[^}]*position:\s*absolute/, "Ana menü işlem kontrolleri kompakt açılır panel olarak stillendirilmeli");
assert.match(app, /function refreshDriveHeaderMenu[\s\S]*configured:\s*"Ayarlar kayıtlı"[\s\S]*driveConnectionBadge/, "Drive paneli kayıtlı ayarı ve bağlantı durumunu göstermeli");
assert.doesNotMatch(app, /function setRestorePromptVisible/, "Drive paneli sayfa açılışında otomatik açılan geri yükleme çağrısı kullanmamalı");
assert.doesNotMatch(html, /appEditMenu|Çalışma modu|Görüntüleme modu|Düzenleme modu/, "Çalışma modu menüsü tamamen kaldırılmalı");
assert.match(app, /backupAndReport\(editing \? "Güncellenen kayıt bekliyor\." : "Yeni kayıt bekliyor\."\)/, "Efor değişiklikleri Drive'a gönderilmek üzere bekleyen olarak işaretlenmeli");
assert.doesNotMatch(app, /Yeni kayıt Drive’a gönderildi|Timesheet üzerinden eklenen efor Drive’a gönderildi/, "Yeni efor ekleme işlemi Drive yedeği tetiklememeli");
assert.match(app, /skipInitialRestore"\)\.addEventListener\("click"[\s\S]*driveHeaderMenu"\)\.open\s*=\s*false/, "Şimdilik değil seçeneği Drive panelini kapatmalı");
assert.match(drive, /LAST_BACKUP_KEY/, "Son Drive sürümü zamanı saklanmalı");
assert.match(drive, /tasks:\s*Array\.isArray/, "Drive yedeği görevleri de içermeli");
assert.match(drive, /people:\s*Array\.isArray/, "Drive yedeği kişileri de içermeli");
assert.match(drive, /jiraItems:\s*Array\.isArray/, "Drive yedeği JIRA maddelerini de içermeli");
assert.match(drive, /reminders:\s*Array\.isArray/, "Drive yedeği hatırlatmaları da içermeli");
assert.match(app, /reminders:\s*window\.ReminderStore\.list\(\)/, "Hatırlatmalar Drive yedek paketine eklenmeli");
assert.match(app, /people:\s*window\.PeopleStore\.list\(\)/, "Kişiler Drive yedek paketine eklenmeli");
assert.match(tasks, /planned.*in_progress.*completed/, "Görev durumları eksik");
assert.match(tasks, /PRIORITIES[\s\S]*high[\s\S]*medium[\s\S]*low/, "Görev öncelik değerleri eksik");
assert.match(tasks, /QUARTERS[\s\S]*Q1[\s\S]*Q4/, "Görev çeyrek değerleri eksik");
assert.match(tasks, /TASK_TYPES[\s\S]*standard[\s\S]*meeting_organization[\s\S]*management_request/, "Görev tipi veri modeli eksik");
assert.match(taskDetailApp, /taskTypeLabel[\s\S]*detailPageAssignee/, "Görev tipi ve atanan kişi ayrı detay sayfasına bağlanmalı");
assert.match(app, /function populateTaskAssigneeOptions[\s\S]*PeopleStore\.list[\s\S]*person\.fullName[\s\S]*person\.email/, "Görev atama listesi tanımlı kişilerden oluşturulmalı");
assert.match(app, /function scheduleTaskAssigneeSearch[\s\S]*setTimeout\(\(\) => searchTaskAssignees\(query\), 300\)/, "Görev atama araması JIRA çağrılarını gecikmeli yapmalı");
assert.match(app, /async function searchTaskAssignees[\s\S]*search\.length < 2[\s\S]*JiraCloudClient\.searchUsers/, "Görev atama alanı iki karakterden sonra JIRA kullanıcılarını anlık aramalı");
assert.match(app, /function selectTaskAssigneeOption[\s\S]*PeopleStore\.mergeJiraUsers[\s\S]*jiraAccountId/, "JIRA'dan seçilen kullanıcı yerel kişi kaydıyla birleştirilerek göreve atanmalı");
assert.match(app, /function selectedTaskAssignment[\s\S]*assigneeId:[\s\S]*person\.id/, "Görev kaydı seçilen kişinin kimliğini ve adını saklamalı");
assert.match(tasks, /assigneeId:[\s\S]*Atanan kişi bağlantısı geçersiz/, "Görev veri modeli kişi bağlantısını doğrulamalı");
assert.match(peopleStore, /function validate[\s\S]*fullName[\s\S]*email[\s\S]*function duplicateEmail[\s\S]*function replaceAll/, "Kişi veri modeli ad-soyad, e-posta tekilliği ve yedek geri yüklemeyi desteklemeli");
assert.match(peopleStore, /function mergeJiraUsers[\s\S]*jiraAccountId[\s\S]*emailMatchIndex[\s\S]*created[\s\S]*updated/, "JIRA kullanıcıları Account ID ve e-posta üzerinden mevcut kişileri koruyarak birleştirilmeli");
assert.match(jiraCloudClient, /function syncUsers[\s\S]*\/users\?/, "JIRA istemcisi aktif kullanıcı senkronizasyonunu desteklemeli");
assert.match(jiraCloudClient, /function searchUsers[\s\S]*query[\s\S]*\/users\?/, "JIRA istemcisi yazılan metinle kullanıcı aramasını desteklemeli");
assert.match(jiraCloudClient, /function searchIssues[\s\S]*query[\s\S]*\/issue-picker\?/, "JIRA istemcisi efor girişinde canlı issue önerisi aramasını desteklemeli");
assert.match(aiServer, /\/api\/jira\/users[\s\S]*\/rest\/api\/3\/users\/search[\s\S]*user\.active[\s\S]*accountType/, "Backend yalnızca aktif Atlassian kullanıcılarını güvenli proxy üzerinden döndürmeli");
assert.match(aiServer, /\/api\/jira\/users[\s\S]*query[\s\S]*\/rest\/api\/3\/user\/search/, "Backend canlı kullanıcı aramasını JIRA'nın kullanıcı arama endpoint'ine iletmeli");
assert.match(jiraEdgeFunction, /pathname === "\/users"[\s\S]*query[\s\S]*\/rest\/api\/3\/user\/search/, "Supabase JIRA proxy canlı kullanıcı aramasını desteklemeli");
assert.match(aiServer, /\/api\/jira\/issue-picker[\s\S]*\/rest\/api\/3\/issue\/picker[\s\S]*summaryText/, "Backend canlı JIRA issue picker sonuçlarını güvenli biçimde dönüştürmeli");
assert.match(jiraEdgeFunction, /pathname === "\/issue-picker"[\s\S]*\/rest\/api\/3\/issue\/picker[\s\S]*summaryText/, "Supabase JIRA proxy canlı issue picker aramasını desteklemeli");
assert.match(aiServer, /\/api\/jira\/issues[\s\S]*for \(let page = 0; page < 10[\s\S]*nextPageToken/, "Backend JIRA issue aramasını sayfalı olarak toplamalı");
assert.match(jiraEdgeFunction, /pathname === "\/issues"[\s\S]*for \(let page = 0; page < 10[\s\S]*nextPageToken/, "Supabase JIRA proxy issue aramasını sayfalı olarak toplamalı");
assert.match(app, /async function syncJiraPeople[\s\S]*JiraCloudClient\.syncUsers[\s\S]*PeopleStore\.mergeJiraUsers[\s\S]*backupAndReport/, "Kişiler ekranı JIRA kullanıcılarını yerel değişiklik olarak içe aktarmalı");
assert.match(app, /function renderPeople[\s\S]*peopleSearchInput[\s\S]*person-avatar[\s\S]*person-source-badge[\s\S]*E-posta JIRA’da gizli/, "Kişiler ekranı JIRA profil bilgilerini, kaynağı ve gizli e-posta durumunu göstermeli");
assert.match(css, /people-sync-panel/, "JIRA kullanıcı senkronizasyon paneli stillendirilmeli");
assert.match(css, /person-avatar[\s\S]*person-source-badge/, "JIRA kullanıcı profil görseli ve kaynak rozeti stillendirilmeli");
assert.match(css, /person-card\[data-source="jira"\]/, "JIRA kaynaklı kişi kartları görsel olarak ayrıştırılmalı");
assert.match(peopleStore, /ROLES[\s\S]*title:[\s\S]*role:[\s\S]*managerId:[\s\S]*function relationshipError/, "Kişi veri modeli ünvan, lider rolü ve yönetici ilişkisini desteklemeli");
assert.match(peopleStore, /Organizasyon yapısında döngü oluşturulamaz/, "Organizasyon şeması döngüsel yönetici bağlantılarını engellemeli");
assert.match(app, /function renderPeople[\s\S]*person-card[\s\S]*mailto:[\s\S]*Düzenle[\s\S]*Sil/, "Kişiler ekranı kişi bakım işlemlerini göstermeli");
assert.match(app, /personForm\.addEventListener\("submit"[\s\S]*PeopleStore\.(?:update|create)[\s\S]*synchronizeTasksForPerson/, "Kişi formu CRUD ve mevcut görev atamalarını koruma akışına bağlanmalı");
assert.match(app, /currentTaskCount[\s\S]*Önce bu görevleri başka bir kişiye atayın/, "Görev atanmış kişi silinmeye karşı korunmalı");
assert.match(html, /data-tab="teamView"[\s\S]*id="teamView"[\s\S]*data-team-tab="peopleView"[\s\S]*data-team-tab="organizationView"[\s\S]*id="organizationLeaderFilter"/, "Kişiler ve organizasyon Ekip ana sekmesinin alt sekmeleri olmalı");
assert.doesNotMatch(html, /class="tab-button"[^>]*data-tab="(?:peopleView|organizationView)"/, "Kişiler ve organizasyon ayrı ana menü öğeleri olmamalı");
assert.match(app, /function activateTeamSubview[\s\S]*team-subtab-button[\s\S]*team-subview/, "Ekip alt sekmeleri bağımsız görünüm değiştirmeli");
assert.match(app, /function renderOrganization\([\s\S]*teamIds[\s\S]*teamTasks[\s\S]*organizationTaskList/, "Seçilen liderin tüm alt ekibine ait görevler gösterilmeli");
assert.doesNotMatch(html, /Raporlama hattı|organizationTreeTitle|id="organizationTree"/, "Organizasyon ekranında raporlama hattı ve ekip yapısı paneli bulunmamalı");
assert.match(css, /organization-layout[^{]*\{[^}]*display:\s*block[\s\S]*organization-task-table/, "Organizasyon ekip iş yükü görünümü tam genişlikte stillendirilmeli");
assert.match(tasks, /function mergeAll/, "Görev planı toplu içe aktarma desteği eksik");
assert.match(tasks, /function ensureHierarchy[\s\S]*parentTaskId/, "Ana görev-alt görev veri bağlantısı eksik");
assert.match(app, /function parseTaskPlanText[\s\S]*priorityMap[\s\S]*quarterEndDate/, "Görev planı TSV ayrıştırıcısı eksik");
assert.match(app, /taskPlanImport[\s\S]*importTaskPlan/, "Görev planı dosya seçimi bağlanmalı");
assert.match(app, /taskPlanPasteForm[\s\S]*importTaskPlanSource/, "Görev planı metin yapıştırma akışı bağlanmalı");
assert.match(app, /function startSubtaskCreate[\s\S]*parentTaskId\.value\s*=\s*parentTask\.id/, "Alt görev ekleme akışı eksik");
assert.match(taskDetailHtml, /id="detailPageAddSubtask"/, "Alt görev ekleme seçeneği ayrı görev detay sayfasında bulunmalı");
assert.match(app, /parentTask[\s\S]*startSubtaskCreate/, "Görev detayından alt görev ekleme rotası bağlanmalı");
assert.match(taskDetailApp, /detailPageSubtaskList[\s\S]*taskUrl\(subtask\.id\)/, "Ayrı görev detay sayfasında alt görev bağlantıları eksik");
assert.match(taskTypeReportApp, /function orderTasksByHierarchy[\s\S]*parentTaskId[\s\S]*depth/, "Görev tipi raporunda ana görev-alt görev sırası korunmalı");
assert.match(taskTypeReportApp, /function detailUrl[\s\S]*new URLSearchParams\(\{ id: taskId, fromType: taskType \}\)[\s\S]*task-detail\.html\?\$\{params\}/, "Görev tipi raporundaki maddeler tekil görev detayına bağlanmalı");
assert.match(app, /function tasksForType[\s\S]*includedIds/, "Görev tipi filtresinde hiyerarşik bağlam korunmalı");
assert.match(app, /taskTypeFilter[\s\S]*tasksForType[\s\S]*renderTasks/, "Görev tipi filtresi rapora bağlanmalı");
assert.match(app, /taskType:\s*"architecture_roadmap"/, "Yapıştırılan görev planı Architecture Roadmap olarak işaretlenmeli");
assert.match(html, /driveSettingsSummary[\s\S]*editDriveSettings[\s\S]*driveSettingsEditor[\s\S]*backupToDrive[\s\S]*restoreFromDrive[\s\S]*skipInitialRestore/, "Drive ayarı ve tüm yedekleme işlemleri tek kompakt panelde olmalı");
assert.match(app, /editDriveSettings"\)\.addEventListener[\s\S]*setDriveSettingsEditing\(true\)[\s\S]*cancelDriveSettings/, "Kayıtlı Drive ayarı yalnızca kullanıcı düzenlemek istediğinde açılmalı");
assert.match(html, /value="week"[\s\S]*value="month"[\s\S]*value="custom"/, "Timesheet dönem seçenekleri eksik");
assert.match(app, /getTimesheetRange/, "Timesheet tarih aralığı hesaplaması eksik");
assert.match(app, /includeWeekends/, "Hafta sonu filtresi eksik");
assert.match(app, /dayTotals/, "Timesheet günlük toplamları eksik");
assert.match(css, /timesheet-scroll[^{]*\{[^}]*overflow-x:\s*auto/, "Timesheet yatay kaydırma eksik");
assert.match(app, /groupedByDate/, "Aynı gün eforlarının tarih bazında gruplanması eksik");
assert.match(app, /formatEffortDays\(dayTotal\)[\s\S]*dayEntries\.length/, "Günlük kayıt sayısı ve gün karşılığı eksik");
assert.doesNotMatch(html, /class="entry-date"/, "Her efor satırında tekrarlanan tarih kutusu olmamalı");
assert.match(app, /dayTotal\s*>=\s*8/, "Günlük 8 saat tamamlanma eşiği eksik");
assert.match(app, /day-progress/, "Günlük efor ilerleme göstergesi eksik");
assert.match(app, /dayTotals.*total\s*>=\s*8/s, "Timesheet 8 saat tamamlanma göstergesi eksik");
assert.match(css, /entry-day-group\.day-complete/, "Tamamlanan gün görsel stili eksik");
assert.match(html, /value="jira"[^>]*selected[\s\S]*value="day"/, "Timesheet JIRA ve günlük satır seçenekleri eksik");
assert.match(app, /issueKey:[\s\S]*jiraItem\?\.name/, "Timesheet satırları JIRA anahtarına bağlanmalı");
assert.match(app, /"Key"[\s\S]*"Issue"[\s\S]*"Priority"/, "Timesheet JIRA sabit sütunları eksik");
assert.match(app, /timesheet-month-row/, "Timesheet ay başlık satırı eksik");
assert.match(app, /group\.days\.set\(entry\.date,\s*\(group\.days\.get\(entry\.date\)/, "Aynı gün eforları tek hücrede toplanmalı");
assert.match(app, /grouping\s*===\s*"day"\s*\?\s*"__daily_summary__"/, "Günlük birleşik Timesheet grubu eksik");
assert.match(app, /function timesheetGroupKey[\s\S]*no-jira:\$\{entry\.id\}/, "JIRA'sı olmayan eforlar Timesheet'te ayrı satırlara ayrılmalı");
assert.match(app, /!hasRealJira\s*\?\s*"JIRA-YOK"[\s\S]*description/, "JIRA'sı olmayan satır kendi efor açıklamasını göstermeli");
assert.match(app, /countLabel\.textContent\s*=\s*`\$\{count\}\s*kayıt`/, "Birleşen günlük kayıt sayısı gösterilmeli");
assert.doesNotMatch(app, /timesheet-row-toggle|expandedTimesheetGroups/, "Timesheet satır kulakçıkları kaldırılmalı");
assert.match(app, /timesheet-effort-button[\s\S]*openEffortEditModal/, "Timesheet efor düzenleme popup bağlantısı eksik");
assert.match(app, /const effortDescription\s*=\s*entriesForCell[\s\S]*entry\.task\s*\|\|\s*entry\.description[\s\S]*effortButton\.title\s*=\s*effortDescription/, "Timesheet eforunun üzerine gelindiğinde efor açıklaması gösterilmeli");
assert.match(app, /jiraSyncCounts[\s\S]*timesheet-jira-sync-summary[\s\S]*"synced", "✓", "JIRA’ya gönderildi"[\s\S]*"imported", "↓", "JIRA’dan alındı"[\s\S]*"local", "○", "JIRA’ya gönderilmedi"[\s\S]*"pending", "↑"[\s\S]*"failed", "!"/, "Timesheet hücreleri JIRA gönderim, içe aktarma ve yerel kayıt durumlarını göstermeli");
assert.match(css, /timesheet-jira-status\[data-status="synced"\][^{]*\{[^}]*background:\s*#1f9d74/, "Timesheet başarılı JIRA gönderimi yeşil simgeyle gösterilmeli");
assert.match(css, /timesheet-jira-status\[data-status="imported"\][^{]*\{[^}]*background:\s*#1f9d74/, "Timesheet JIRA’dan alınan eforu yeşil simgeyle göstermeli");
assert.match(css, /timesheet-jira-status\[data-status="local"\][^{]*\{[^}]*background:\s*#d29b19/, "Timesheet JIRA’ya gönderilmeyen yerel eforu sarı simgeyle göstermeli");
assert.match(app, /timesheet-empty-effort-button[\s\S]*openEffortCreateModal\(row\.jiraId, iso\)/, "Boş Timesheet hücresinden JIRA ve tarih bazlı efor ekleme eksik");
assert.match(app, /function openEffortCreateModal[\s\S]*modalDateInput[\s\S]*showModal/, "Yeni Timesheet efor popup akışı eksik");
assert.match(html, /id="modalRepeatEntryToggle"[\s\S]*Ardışık çoklu giriş[\s\S]*yalnızca tarih ve süreyi girersiniz/, "Efor popup'ında ardışık çoklu giriş seçeneği bulunmalı");
assert.match(app, /function renderRepeatEntryMode[\s\S]*modalRepeatEntryToggle[\s\S]*Kaydet ve yeni giriş aç/, "Çoklu giriş seçeneği kaydetme düğmesini ardışık giriş moduna çevirmeli");
assert.match(app, /const repeatEntry = \$\("#modalRepeatEntryToggle"\)\.checked[\s\S]*saveEntry\(\{ \.\.\.payload, date:[\s\S]*syncEffortToJira[\s\S]*if \(repeatEntry\)[\s\S]*modalDateInput"\)\.value = ""[\s\S]*modalHoursInput"\)\.value = ""[\s\S]*modalDateInput"\)\.focus\(\)/, "Ardışık çoklu girişte kayıt sonrası yalnızca tarih ve süre temizlenip popup açık kalmalı");
assert.match(css, /repeat-entry-toggle:has\(input:checked\)/, "Ardışık çoklu giriş seçimi görsel olarak belirtilmeli");
assert.match(css, /timesheet-empty-effort-button/, "Boş Timesheet hücresi ekleme düğmesi stili eksik");
assert.match(app, /effortEditModalForm\.addEventListener\("submit"[\s\S]*getStore\(\)\.update/, "Popup üzerinden efor revizyonu eksik");
assert.match(deleteEffortBlock, /confirm\([\s\S]*removeEntry\(entry\.id\)[\s\S]*render\(\)/, "Efor silme işlemi kullanıcı onayıyla çalışmalı");
assert.doesNotMatch(deleteEffortBlock, /backupAndReport|Drive/, "Efor silme işlemi Drive yedeği tetiklememeli");
assert.doesNotMatch(effortModalSubmitBlock.slice(0, effortModalSubmitBlock.indexOf("const result = entry")), /backupAndReport|Drive’a gönderildi/, "Timesheet efor ekleme işlemi Drive yedeği tetiklememeli");
assert.match(app, /deleteEffortModal"\)\.addEventListener\("click"[\s\S]*deleteEffortEntry\(entry\)[\s\S]*closeEffortModal/, "Timesheet düzenleme popup'ı efor silme akışına bağlanmalı");
assert.match(app, /jiraWorklogId[\s\S]*bağlı JIRA worklog da silinsin mi[\s\S]*JiraCloudClient\.deleteWorklog/, "Efora bağlı JIRA worklog ayrı onayla silinebilmeli");
assert.match(app, /issueSummary:[\s\S]*jiraItem\?\.description/, "Timesheet Issue alanında JIRA summary gösterilmeli");
assert.match(html, /entry-jira-summary[\s\S]*entry-effort-description/, "Efor geçmişinde JIRA summary ve efor açıklaması ayrılmalı");
assert.match(app, /jiraId:\s*fields\.jiraId\.value/, "Efor kaydında JIRA seçimi saklanmalı");
assert.match(app, /id:\s*"__dummy_jira__"[\s\S]*name:\s*"JIRA-YOK"/, "Geçici dummy JIRA tanımı eksik");
assert.match(html, /id="jiraItemInput"[\s\S]*JIRA-YOK/, "Efor formunda geçici JIRA seçeneği açıklanmalı");
assert.match(app, /const getJiraItem[\s\S]*DUMMY_JIRA/, "Dummy JIRA kayıt çözümleme akışına bağlanmalı");
assert.match(jira, /name.*description.*url/s, "JIRA adı, açıklaması ve URL alanları eksik");
assert.match(app, /JIRA_TABLE_COLUMNS[\s\S]*Issue Type[\s\S]*Key[\s\S]*Summary[\s\S]*Assignee[\s\S]*Reporter[\s\S]*Priority[\s\S]*Status[\s\S]*Resolution[\s\S]*Created[\s\S]*Updated[\s\S]*Due date/, "JIRA tablo sütunları eksik");
assert.match(app, /function renderJiraTableHeader[\s\S]*draggable\s*=\s*true[\s\S]*dragstart[\s\S]*drop/, "JIRA kolonları sürükle-bırak ile sıralanabilmeli");
assert.match(app, /function beginJiraColumnResize[\s\S]*pointermove[\s\S]*jiraTableLayout\.widths/, "JIRA kolon genişlikleri kullanıcı tarafından değiştirilebilmeli");
assert.match(app, /function renderJiraColumnOptions[\s\S]*checkbox[\s\S]*jiraTableLayout\.visible/, "JIRA kolonları görünümden çıkarılıp yeniden eklenebilmeli");
assert.match(app, /function autoFitJiraColumns[\s\S]*scrollWidth[\s\S]*applyJiraColumnWidths/, "JIRA kolonları içerik genişliğine otomatik sığdırılmalı");
assert.match(app, /function scheduleJiraAutoFit[\s\S]*requestAnimationFrame[\s\S]*autoFitJiraColumns\(false\)/, "JIRA otomatik sığdırma görünür tablo yerleşiminden sonra çalışmalı");
assert.match(app, /function activateMainView[\s\S]*mainViewId === "jiraView"[\s\S]*activateJiraSubview\("jiraItemsView"\)[\s\S]*function activateJiraSubview[\s\S]*viewId === "jiraItemsView"[\s\S]*scheduleJiraAutoFit\(\)/, "JIRA Maddeleri tabı açıldığında madde görünümüne geçilmeli ve kolonlar yeniden sığdırılmalı");
assert.match(css, /jira-issue-table[^{]*\{[^}]*width:\s*max-content[\s\S]*jira-column-resizer[^{]*\{[^}]*cursor:\s*col-resize/, "JIRA tablosu sıkı içerik genişliği ve kolon boyutlandırma tutamacı kullanmalı");
assert.match(app, /DOMParser[\s\S]*#issuetable/, "JIRA HTML içe aktarma ayrıştırıcısı eksik");
assert.match(jira, /mergeAll/, "JIRA HTML kayıtlarını birleştirme desteği eksik");
assert.match(jira, /normalizeKey[\s\S]*duplicateCount[\s\S]*idRemap/, "JIRA HTML içe aktarımında Key tekilleştirme ve bağlantı eşleme desteği eksik");
assert.match(app, /function relinkMergedJiraEntries[\s\S]*idRemap\[entry\.jiraId\]/, "Mükerrer JIRA'ya bağlı eforlar korunan JIRA kaydına taşınmalı");
assert.doesNotMatch(app, /(?:pagehide|visibilitychange)[\s\S]{0,500}backupLocalDataToDrive/, "Drive yedeği yalnızca kullanıcı Kaydet dediğinde gönderilmeli");
assert.doesNotMatch(app, /APP_EDIT_SESSION_KEY|requireAppEditMode|setAppEditMode|EDIT_ACTION_SELECTOR/, "Veri değiştiren kontroller çalışma modu ile kilitlenmemeli");
assert.doesNotMatch(css, /body:not\(\.app-edit-mode\)/, "Düzenleme işlemleri CSS ile çalışma moduna göre devre dışı bırakılmamalı");
assert.match(cloudDataRuntime, /const records = new Map[\s\S]*function write[\s\S]*upserts[\s\S]*deletedIds[\s\S]*function suspend/, "Uygulama verileri yalnızca bellekte tutulup değişiklikler izlenmeli");
assert.doesNotMatch([dataStore, tasks, peopleStore, jira, reminders].join("\n"), /localStorage\.(?:getItem|setItem)/, "Efor, görev, kişi, JIRA ve hatırlatma mağazaları localStorage kullanmamalı");
assert.match(app, /function submitSupabaseCredentials[\s\S]*SupabaseCloud\.signUp[\s\S]*SupabaseCloud\.signIn[\s\S]*supabaseAuthForm"\)\.addEventListener\("submit"[\s\S]*supabaseSignUp"\)\.addEventListener[\s\S]*supabaseForgotPassword[\s\S]*sendPasswordReset/, "Supabase hesap menüsü giriş, kayıt ve e-posta şifre yenilemeye bağlanmalı");
assert.ok(html.indexOf('id="loginScreen"') < html.indexOf('class="page-header"'), "Supabase giriş ekranı uygulama içeriğinden önce gösterilmeli");
assert.match(app, /function submitSupabaseCredentials[\s\S]*SupabaseCloud\.signUp[\s\S]*SupabaseCloud\.signIn[\s\S]*loginScreenForm"\)\.addEventListener\("submit"[\s\S]*loginScreenSignUp"\)\.addEventListener[\s\S]*loginScreenForgotPassword[\s\S]*sendPasswordReset/, "Tam ekran giriş sayfası Supabase giriş, kayıt ve şifre yenileme akışlarına bağlanmalı");
assert.match(app, /function setLoginScreenVisible[\s\S]*auth-required[\s\S]*function refreshSupabaseAccount[\s\S]*setLoginScreenVisible\(!signedIn\)/, "Supabase oturumu giriş ekranının görünürlüğünü yönetmeli");
assert.match(css, /login-screen[^{]*\{[^}]*position:\s*fixed[\s\S]*login-shell[^{]*\{[^}]*grid-template-columns[\s\S]*@media\s*\(max-width:\s*850px\)[\s\S]*login-shell[^{]*\{[^}]*grid-template-columns:\s*1fr/, "Giriş ekranı masaüstü ve mobilde duyarlı olmalı");
assert.match(supabaseCloudClient, /auth\.signOut\(\{\s*scope:\s*"local"\s*\}\)/, "Çıkış yalnızca mevcut Supabase oturumunu kapatmalı");
assert.match(app, /function refreshSupabaseAccount[\s\S]*ensureCloudDataLoaded\(\)[\s\S]*function pullFromSupabase[\s\S]*replaceLocalBundle[\s\S]*setCloudDataGate\("ready"\)/, "Supabase oturumu açıldığında bulut verileri otomatik yüklenmeli");
assert.match(app, /function queueCloudChange[\s\S]*SupabaseCloud\.applyChanges\(change\)[\s\S]*Tüm değişiklikler Supabase’e kaydedildi/, "Her bellek değişikliği otomatik olarak Supabase'e gönderilmeli");
assert.match(app, /taskForm\.addEventListener\("submit"[\s\S]*TaskStore\.(?:update|create)[\s\S]*await waitForDataSaves\(\)[\s\S]*Görev bellekte geri alındı/, "Görev formu başarı bildirmeden önce Supabase kaydını beklemeli ve hata halinde belleği geri almalı");
assert.match(app, /async function pullFromSupabase[\s\S]*await waitForDataSaves\(\)[\s\S]*SupabaseCloud\.pullBundle/, "Buluttan yenileme bekleyen kayıtları tamamlamadan belleği değiştirmemeli");
assert.match(app, /addEventListener\("beforeunload"[\s\S]*cloudSavePending[\s\S]*event\.preventDefault/, "Bekleyen Supabase kaydı sırasında sayfa yenileme uyarısı gösterilmeli");
assert.match(app, /CloudDataRuntime\.setChangeHandler\(queueCloudChange\)/, "Bulut çalışma katmanı otomatik Supabase kaydına bağlanmalı");
assert.doesNotMatch(html, /id="supabasePush"|Yerel verileri gönder|Supabase’den yükle/, "Bulut-öncelikli uygulamada manuel yerel veri gönderme akışı bulunmamalı");
assert.match(taskDetailApp, /initializeTaskDetail[\s\S]*SupabaseCloud\.getSession[\s\S]*SupabaseCloud\.pullBundle[\s\S]*TaskStore\.replaceAll/, "Görev detay sayfası veriyi Supabase'den yüklemeli");
assert.match(taskTypeReportApp, /initializeTaskTypeReport[\s\S]*SupabaseCloud\.getSession[\s\S]*SupabaseCloud\.pullBundle[\s\S]*TaskStore\.replaceAll/, "Görev tipi raporu veriyi Supabase'den yüklemeli");
assert.match(drive, /keepalive:\s*Boolean\(options\.keepalive\)/, "Kapanış isteği keepalive kullanmalı");

console.log("✓ frontend DOM/veri katmanı sözleşmesi");
console.log("✓ responsive kırılımlar ve güvenli metin render kontrolü");
